/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TheLinkedAccountsOfTheUserInner model module.
 * @module model/TheLinkedAccountsOfTheUserInner
 * @version 2025-03-25
 */
class TheLinkedAccountsOfTheUserInner {
    /**
     * Constructs a new <code>TheLinkedAccountsOfTheUserInner</code>.
     * @alias module:model/TheLinkedAccountsOfTheUserInner
     * @param accountID {String} The account ID
     * @param accountType {module:model/TheLinkedAccountsOfTheUserInner.AccountTypeEnum} The account type
     */
    constructor(accountID, accountType) { 
        
        TheLinkedAccountsOfTheUserInner.initialize(this, accountID, accountType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accountID, accountType) { 
        obj['accountID'] = accountID;
        obj['accountType'] = accountType;
    }

    /**
     * Constructs a <code>TheLinkedAccountsOfTheUserInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TheLinkedAccountsOfTheUserInner} obj Optional instance to populate.
     * @return {module:model/TheLinkedAccountsOfTheUserInner} The populated <code>TheLinkedAccountsOfTheUserInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TheLinkedAccountsOfTheUserInner();

            if (data.hasOwnProperty('accountID')) {
                obj['accountID'] = ApiClient.convertToType(data['accountID'], 'String');
            }
            if (data.hasOwnProperty('accountType')) {
                obj['accountType'] = ApiClient.convertToType(data['accountType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TheLinkedAccountsOfTheUserInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TheLinkedAccountsOfTheUserInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TheLinkedAccountsOfTheUserInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['accountID'] && !(typeof data['accountID'] === 'string' || data['accountID'] instanceof String)) {
            throw new Error("Expected the field `accountID` to be a primitive type in the JSON string but got " + data['accountID']);
        }
        // ensure the json data is a string
        if (data['accountType'] && !(typeof data['accountType'] === 'string' || data['accountType'] instanceof String)) {
            throw new Error("Expected the field `accountType` to be a primitive type in the JSON string but got " + data['accountType']);
        }

        return true;
    }


}

TheLinkedAccountsOfTheUserInner.RequiredProperties = ["accountID", "accountType"];

/**
 * The account ID
 * @member {String} accountID
 */
TheLinkedAccountsOfTheUserInner.prototype['accountID'] = undefined;

/**
 * The account type
 * @member {module:model/TheLinkedAccountsOfTheUserInner.AccountTypeEnum} accountType
 */
TheLinkedAccountsOfTheUserInner.prototype['accountType'] = undefined;





/**
 * Allowed values for the <code>accountType</code> property.
 * @enum {String}
 * @readonly
 */
TheLinkedAccountsOfTheUserInner['AccountTypeEnum'] = {

    /**
     * value: "discord"
     * @const
     */
    "discord": "discord",

    /**
     * value: "telegram"
     * @const
     */
    "telegram": "telegram",

    /**
     * value: "embed"
     * @const
     */
    "embed": "embed"
};



export default TheLinkedAccountsOfTheUserInner;

