/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ApiKeysInvitesCodeRedeemPost200Response model module.
 * @module model/V1ApiKeysInvitesCodeRedeemPost200Response
 * @version 2025-03-25
 */
class V1ApiKeysInvitesCodeRedeemPost200Response {
    /**
     * Constructs a new <code>V1ApiKeysInvitesCodeRedeemPost200Response</code>.
     * @alias module:model/V1ApiKeysInvitesCodeRedeemPost200Response
     * @extends Object
     * @param success {module:model/V1ApiKeysInvitesCodeRedeemPost200Response.SuccessEnum} 
     * @param apiKey {String} The API key you will need to use to authenticate your requests. The key cannot be retrieved again after it is created: keep it safe.
     * @param organizationID {String} The ID of the organization you have just created. You will need this ID to communicate with our team. Keep it safe.
     * @param validUntil {String} The date until which the API subscroption is valid.
     */
    constructor(success, apiKey, organizationID, validUntil) { 
        
        V1ApiKeysInvitesCodeRedeemPost200Response.initialize(this, success, apiKey, organizationID, validUntil);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, apiKey, organizationID, validUntil) { 
        obj['success'] = success;
        obj['apiKey'] = apiKey;
        obj['organizationID'] = organizationID;
        obj['validUntil'] = validUntil;
    }

    /**
     * Constructs a <code>V1ApiKeysInvitesCodeRedeemPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ApiKeysInvitesCodeRedeemPost200Response} obj Optional instance to populate.
     * @return {module:model/V1ApiKeysInvitesCodeRedeemPost200Response} The populated <code>V1ApiKeysInvitesCodeRedeemPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ApiKeysInvitesCodeRedeemPost200Response();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('organizationID')) {
                obj['organizationID'] = ApiClient.convertToType(data['organizationID'], 'String');
            }
            if (data.hasOwnProperty('validUntil')) {
                obj['validUntil'] = ApiClient.convertToType(data['validUntil'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ApiKeysInvitesCodeRedeemPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ApiKeysInvitesCodeRedeemPost200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ApiKeysInvitesCodeRedeemPost200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['apiKey'] && !(typeof data['apiKey'] === 'string' || data['apiKey'] instanceof String)) {
            throw new Error("Expected the field `apiKey` to be a primitive type in the JSON string but got " + data['apiKey']);
        }
        // ensure the json data is a string
        if (data['organizationID'] && !(typeof data['organizationID'] === 'string' || data['organizationID'] instanceof String)) {
            throw new Error("Expected the field `organizationID` to be a primitive type in the JSON string but got " + data['organizationID']);
        }
        // ensure the json data is a string
        if (data['validUntil'] && !(typeof data['validUntil'] === 'string' || data['validUntil'] instanceof String)) {
            throw new Error("Expected the field `validUntil` to be a primitive type in the JSON string but got " + data['validUntil']);
        }

        return true;
    }


}

V1ApiKeysInvitesCodeRedeemPost200Response.RequiredProperties = ["success", "apiKey", "organizationID", "validUntil"];

/**
 * @member {module:model/V1ApiKeysInvitesCodeRedeemPost200Response.SuccessEnum} success
 */
V1ApiKeysInvitesCodeRedeemPost200Response.prototype['success'] = undefined;

/**
 * The API key you will need to use to authenticate your requests. The key cannot be retrieved again after it is created: keep it safe.
 * @member {String} apiKey
 */
V1ApiKeysInvitesCodeRedeemPost200Response.prototype['apiKey'] = undefined;

/**
 * The ID of the organization you have just created. You will need this ID to communicate with our team. Keep it safe.
 * @member {String} organizationID
 */
V1ApiKeysInvitesCodeRedeemPost200Response.prototype['organizationID'] = undefined;

/**
 * The date until which the API subscroption is valid.
 * @member {String} validUntil
 */
V1ApiKeysInvitesCodeRedeemPost200Response.prototype['validUntil'] = undefined;





/**
 * Allowed values for the <code>success</code> property.
 * @enum {Boolean}
 * @readonly
 */
V1ApiKeysInvitesCodeRedeemPost200Response['SuccessEnum'] = {

    /**
     * value: "true"
     * @const
     */
    "true": "true"
};



export default V1ApiKeysInvitesCodeRedeemPost200Response;

