/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ApiKeysInvitesCodeRedeemPostRequest model module.
 * @module model/V1ApiKeysInvitesCodeRedeemPostRequest
 * @version 2025-03-25
 */
class V1ApiKeysInvitesCodeRedeemPostRequest {
    /**
     * Constructs a new <code>V1ApiKeysInvitesCodeRedeemPostRequest</code>.
     * @alias module:model/V1ApiKeysInvitesCodeRedeemPostRequest
     * @extends Object
     * @param organizationName {String} The name of the organization you want to create.
     * @param name {String} The name of the point of contact for the API subscription.
     * @param email {String} The email of the point of contact for the API subscription.
     */
    constructor(organizationName, name, email) { 
        
        V1ApiKeysInvitesCodeRedeemPostRequest.initialize(this, organizationName, name, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, organizationName, name, email) { 
        obj['organizationName'] = organizationName;
        obj['name'] = name;
        obj['email'] = email;
    }

    /**
     * Constructs a <code>V1ApiKeysInvitesCodeRedeemPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ApiKeysInvitesCodeRedeemPostRequest} obj Optional instance to populate.
     * @return {module:model/V1ApiKeysInvitesCodeRedeemPostRequest} The populated <code>V1ApiKeysInvitesCodeRedeemPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ApiKeysInvitesCodeRedeemPostRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('organizationName')) {
                obj['organizationName'] = ApiClient.convertToType(data['organizationName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ApiKeysInvitesCodeRedeemPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ApiKeysInvitesCodeRedeemPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ApiKeysInvitesCodeRedeemPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['organizationName'] && !(typeof data['organizationName'] === 'string' || data['organizationName'] instanceof String)) {
            throw new Error("Expected the field `organizationName` to be a primitive type in the JSON string but got " + data['organizationName']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

V1ApiKeysInvitesCodeRedeemPostRequest.RequiredProperties = ["organizationName", "name", "email"];

/**
 * The name of the organization you want to create.
 * @member {String} organizationName
 */
V1ApiKeysInvitesCodeRedeemPostRequest.prototype['organizationName'] = undefined;

/**
 * The name of the point of contact for the API subscription.
 * @member {String} name
 */
V1ApiKeysInvitesCodeRedeemPostRequest.prototype['name'] = undefined;

/**
 * The email of the point of contact for the API subscription.
 * @member {String} email
 */
V1ApiKeysInvitesCodeRedeemPostRequest.prototype['email'] = undefined;






export default V1ApiKeysInvitesCodeRedeemPostRequest;

