/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage model module.
 * @module model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage
 * @version 2025-03-25
 */
class V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage {
    /**
     * Constructs a new <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage</code>.
     * Usage statistics for the completion request.
     * @alias module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage
     * @param promptTokens {Number} Number of tokens in the prompt.
     * @param completionTokens {Number} Number of tokens in the generated completion.
     * @param totalTokens {Number} Total number of tokens used (prompt + completion).
     */
    constructor(promptTokens, completionTokens, totalTokens) { 
        
        V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.initialize(this, promptTokens, completionTokens, totalTokens);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, promptTokens, completionTokens, totalTokens) { 
        obj['prompt_tokens'] = promptTokens;
        obj['completion_tokens'] = completionTokens;
        obj['total_tokens'] = totalTokens;
    }

    /**
     * Constructs a <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage} obj Optional instance to populate.
     * @return {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage} The populated <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage();

            if (data.hasOwnProperty('prompt_tokens')) {
                obj['prompt_tokens'] = ApiClient.convertToType(data['prompt_tokens'], 'Number');
            }
            if (data.hasOwnProperty('completion_tokens')) {
                obj['completion_tokens'] = ApiClient.convertToType(data['completion_tokens'], 'Number');
            }
            if (data.hasOwnProperty('total_tokens')) {
                obj['total_tokens'] = ApiClient.convertToType(data['total_tokens'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.RequiredProperties = ["prompt_tokens", "completion_tokens", "total_tokens"];

/**
 * Number of tokens in the prompt.
 * @member {Number} prompt_tokens
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.prototype['prompt_tokens'] = undefined;

/**
 * Number of tokens in the generated completion.
 * @member {Number} completion_tokens
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.prototype['completion_tokens'] = undefined;

/**
 * Total number of tokens used (prompt + completion).
 * @member {Number} total_tokens
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.prototype['total_tokens'] = undefined;






export default V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage;

