/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner from './V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage from './V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage';

/**
 * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response model module.
 * @module model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response
 * @version 2025-03-25
 */
class V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response {
    /**
     * Constructs a new <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response</code>.
     * The response format for chat completions.
     * @alias module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response
     * @param id {String} A unique identifier for the chat completion.
     * @param created {Number} The Unix timestamp (in seconds) of when the chat completion was created.
     * @param object {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.ObjectEnum} The object type, which is always \"chat.completion\"
     * @param model {String} The model used for the chat completion.
     * @param choices {Array.<module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner>} An array of chat completion choices.
     * @param usage {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage} 
     */
    constructor(id, created, object, model, choices, usage) { 
        
        V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.initialize(this, id, created, object, model, choices, usage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, created, object, model, choices, usage) { 
        obj['id'] = id;
        obj['created'] = created;
        obj['object'] = object;
        obj['model'] = model;
        obj['choices'] = choices;
        obj['usage'] = usage;
    }

    /**
     * Constructs a <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response} obj Optional instance to populate.
     * @return {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response} The populated <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], [V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner]);
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.constructFromObject(data['usage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        if (data['choices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['choices'])) {
                throw new Error("Expected the field `choices` to be an array in the JSON data but got " + data['choices']);
            }
            // validate the optional field `choices` (array)
            for (const item of data['choices']) {
                V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.validateJSON(item);
            };
        }
        // validate the optional field `usage`
        if (data['usage']) { // data not null
          V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage.validateJSON(data['usage']);
        }

        return true;
    }


}

V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.RequiredProperties = ["id", "created", "object", "model", "choices", "usage"];

/**
 * A unique identifier for the chat completion.
 * @member {String} id
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.prototype['id'] = undefined;

/**
 * The Unix timestamp (in seconds) of when the chat completion was created.
 * @member {Number} created
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.prototype['created'] = undefined;

/**
 * The object type, which is always \"chat.completion\"
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.ObjectEnum} object
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.prototype['object'] = undefined;

/**
 * The model used for the chat completion.
 * @member {String} model
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.prototype['model'] = undefined;

/**
 * An array of chat completion choices.
 * @member {Array.<module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner>} choices
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.prototype['choices'] = undefined;

/**
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage} usage
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response.prototype['usage'] = undefined;





/**
 * Allowed values for the <code>object</code> property.
 * @enum {String}
 * @readonly
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response['ObjectEnum'] = {

    /**
     * value: "chat.completion"
     * @const
     */
    "chat.completion": "chat.completion"
};



export default V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response;

