/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner from './V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner';
import V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData from './V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData';

/**
 * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest model module.
 * @module model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest
 * @version 2025-03-25
 */
class V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest {
    /**
     * Constructs a new <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest</code>.
     * @alias module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest
     * @param messages {Array.<module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner>} A list of messages that make up the conversation context. Only the last message is used for completion.
     */
    constructor(messages) { 
        
        V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.initialize(this, messages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messages) { 
        obj['messages'] = messages;
        obj['store'] = true;
        obj['source'] = 'web';
    }

    /**
     * Constructs a <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest} obj Optional instance to populate.
     * @return {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest} The populated <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], [V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner]);
            }
            if (data.hasOwnProperty('store')) {
                obj['store'] = ApiClient.convertToType(data['store'], 'Boolean');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('discord_data')) {
                obj['discord_data'] = V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.constructFromObject(data['discord_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['messages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['messages'])) {
                throw new Error("Expected the field `messages` to be an array in the JSON data but got " + data['messages']);
            }
            // validate the optional field `messages` (array)
            for (const item of data['messages']) {
                V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
            throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
        }

        return true;
    }


}

V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.RequiredProperties = ["messages"];

/**
 * A list of messages that make up the conversation context. Only the last message is used for completion.
 * @member {Array.<module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner>} messages
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.prototype['messages'] = undefined;

/**
 * When set to false, historical messages are not used in the context, and the message is not appended to the conversation history.
 * @member {Boolean} store
 * @default true
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.prototype['store'] = true;

/**
 * The place where the conversation is happening, which informs where the message should be saved in the chat history if `store` is true.
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.SourceEnum} source
 * @default 'web'
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.prototype['source'] = 'web';

/**
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData} discord_data
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest.prototype['discord_data'] = undefined;





/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest['SourceEnum'] = {

    /**
     * value: "discord"
     * @const
     */
    "discord": "discord",

    /**
     * value: "embed"
     * @const
     */
    "embed": "embed",

    /**
     * value: "web"
     * @const
     */
    "web": "web"
};



export default V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest;

