/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage model module.
 * @module model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage
 * @version 2025-03-25
 */
class V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage {
    /**
     * Constructs a new <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage</code>.
     * The message generated by the model.
     * @alias module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage
     * @param role {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.RoleEnum} The role of the message author, which is always \"assistant\" for completions.
     * @param content {String} The content of the message.
     */
    constructor(role, content) { 
        
        V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.initialize(this, role, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, role, content) { 
        obj['role'] = role;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage} obj Optional instance to populate.
     * @return {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage} The populated <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage();

            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('tool_calls')) {
                obj['tool_calls'] = ApiClient.convertToType(data['tool_calls'], [Object]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tool_calls'])) {
            throw new Error("Expected the field `tool_calls` to be an array in the JSON data but got " + data['tool_calls']);
        }

        return true;
    }


}

V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.RequiredProperties = ["role", "content"];

/**
 * The role of the message author, which is always \"assistant\" for completions.
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.RoleEnum} role
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.prototype['role'] = undefined;

/**
 * The content of the message.
 * @member {String} content
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.prototype['content'] = undefined;

/**
 * The tool calls generated by the model, such as function calls.
 * @member {Array.<Object>} tool_calls
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.prototype['tool_calls'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage['RoleEnum'] = {

    /**
     * value: "assistant"
     * @const
     */
    "assistant": "assistant"
};



export default V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage;

