/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner model module.
 * @module model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner
 * @version 2025-03-25
 */
class V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner {
    /**
     * Constructs a new <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner</code>.
     * @alias module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner
     * @param role {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.RoleEnum} The role of the message author. Can be \"assistant\", \"developer\", \"system\", \"tool\", or \"user\".
     * @param content {String} The content of the message.
     */
    constructor(role, content) { 
        
        V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.initialize(this, role, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, role, content) { 
        obj['role'] = role;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner} obj Optional instance to populate.
     * @return {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner} The populated <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner();

            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.RequiredProperties = ["role", "content"];

/**
 * The role of the message author. Can be \"assistant\", \"developer\", \"system\", \"tool\", or \"user\".
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.RoleEnum} role
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.prototype['role'] = undefined;

/**
 * The content of the message.
 * @member {String} content
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.prototype['content'] = undefined;

/**
 * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
 * @member {String} name
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner.prototype['name'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner['RoleEnum'] = {

    /**
     * value: "assistant"
     * @const
     */
    "assistant": "assistant",

    /**
     * value: "developer"
     * @const
     */
    "developer": "developer",

    /**
     * value: "system"
     * @const
     */
    "system": "system",

    /**
     * value: "tool"
     * @const
     */
    "tool": "tool",

    /**
     * value: "user"
     * @const
     */
    "user": "user"
};



export default V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner;

