/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage from './V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage';

/**
 * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner model module.
 * @module model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner
 * @version 2025-03-25
 */
class V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner {
    /**
     * Constructs a new <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner</code>.
     * @alias module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner
     * @param index {Number} The index of the choice in the array.
     * @param message {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage} 
     * @param finishReason {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.FinishReasonEnum} The reason the model stopped generating tokens.
     */
    constructor(index, message, finishReason) { 
        
        V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.initialize(this, index, message, finishReason);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, index, message, finishReason) { 
        obj['index'] = index;
        obj['message'] = message;
        obj['finish_reason'] = finishReason;
    }

    /**
     * Constructs a <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner} obj Optional instance to populate.
     * @return {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner} The populated <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner();

            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.constructFromObject(data['message']);
            }
            if (data.hasOwnProperty('logprobs')) {
                obj['logprobs'] = ApiClient.convertToType(data['logprobs'], Object);
            }
            if (data.hasOwnProperty('finish_reason')) {
                obj['finish_reason'] = ApiClient.convertToType(data['finish_reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `message`
        if (data['message']) { // data not null
          V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage.validateJSON(data['message']);
        }
        // ensure the json data is a string
        if (data['finish_reason'] && !(typeof data['finish_reason'] === 'string' || data['finish_reason'] instanceof String)) {
            throw new Error("Expected the field `finish_reason` to be a primitive type in the JSON string but got " + data['finish_reason']);
        }

        return true;
    }


}

V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.RequiredProperties = ["index", "message", "finish_reason"];

/**
 * The index of the choice in the array.
 * @member {Number} index
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.prototype['index'] = undefined;

/**
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage} message
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.prototype['message'] = undefined;

/**
 * @member {Object} logprobs
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.prototype['logprobs'] = undefined;

/**
 * The reason the model stopped generating tokens.
 * @member {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.FinishReasonEnum} finish_reason
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner.prototype['finish_reason'] = undefined;





/**
 * Allowed values for the <code>finish_reason</code> property.
 * @enum {String}
 * @readonly
 */
V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner['FinishReasonEnum'] = {

    /**
     * value: "stop"
     * @const
     */
    "stop": "stop",

    /**
     * value: "length"
     * @const
     */
    "length": "length",

    /**
     * value: "tool_calls"
     * @const
     */
    "tool_calls": "tool_calls",

    /**
     * value: "content_filter"
     * @const
     */
    "content_filter": "content_filter",

    /**
     * value: "function_call"
     * @const
     */
    "function_call": "function_call"
};



export default V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner;

