/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasPost201Response model module.
 * @module model/V1ReplicasPost201Response
 * @version 2025-03-25
 */
class V1ReplicasPost201Response {
    /**
     * Constructs a new <code>V1ReplicasPost201Response</code>.
     * @alias module:model/V1ReplicasPost201Response
     * @param success {Boolean} Indicates if the replica was created successfully
     * @param uuid {String} The replica UUID
     */
    constructor(success, uuid) { 
        
        V1ReplicasPost201Response.initialize(this, success, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, uuid) { 
        obj['success'] = success;
        obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>V1ReplicasPost201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasPost201Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasPost201Response} The populated <code>V1ReplicasPost201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasPost201Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasPost201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasPost201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasPost201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }

        return true;
    }


}

V1ReplicasPost201Response.RequiredProperties = ["success", "uuid"];

/**
 * Indicates if the replica was created successfully
 * @member {Boolean} success
 */
V1ReplicasPost201Response.prototype['success'] = undefined;

/**
 * The replica UUID
 * @member {String} uuid
 */
V1ReplicasPost201Response.prototype['uuid'] = undefined;






export default V1ReplicasPost201Response;

