/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasGet200ResponseItemsInnerLlm from './V1ReplicasGet200ResponseItemsInnerLlm';

/**
 * The V1ReplicasReplicaUUIDGet200Response model module.
 * @module model/V1ReplicasReplicaUUIDGet200Response
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDGet200Response {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDGet200Response</code>.
     * @alias module:model/V1ReplicasReplicaUUIDGet200Response
     * @extends Object
     * @param name {String} The name of the replica.
     * @param shortDescription {String} A short description of your replica. This field is not used for training the replica.
     * @param greeting {String} The first thing your replica will say when you start a conversation with them.
     * @param ownerID {String} The replica owner ID.
     * @param slug {String} The slug of the replica. Slugs can be used by API consumers to determine the URLs where replicas can be found.
     * @param llm {module:model/V1ReplicasGet200ResponseItemsInnerLlm} 
     * @param uuid {String} The replica UUID
     */
    constructor(name, shortDescription, greeting, ownerID, slug, llm, uuid) { 
        
        V1ReplicasReplicaUUIDGet200Response.initialize(this, name, shortDescription, greeting, ownerID, slug, llm, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, shortDescription, greeting, ownerID, slug, llm, uuid) { 
        obj['name'] = name;
        obj['shortDescription'] = shortDescription;
        obj['greeting'] = greeting;
        obj['type'] = 'character';
        obj['ownerID'] = ownerID;
        obj['private'] = false;
        obj['slug'] = slug;
        obj['profileImage'] = 'https://sensay.io/assets/default-replica-profile.webp';
        obj['llm'] = llm;
        obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDGet200Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDGet200Response} The populated <code>V1ReplicasReplicaUUIDGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDGet200Response();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('purpose')) {
                obj['purpose'] = ApiClient.convertToType(data['purpose'], 'String');
            }
            if (data.hasOwnProperty('shortDescription')) {
                obj['shortDescription'] = ApiClient.convertToType(data['shortDescription'], 'String');
            }
            if (data.hasOwnProperty('greeting')) {
                obj['greeting'] = ApiClient.convertToType(data['greeting'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('ownerID')) {
                obj['ownerID'] = ApiClient.convertToType(data['ownerID'], 'String');
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
            if (data.hasOwnProperty('whitelistEmails')) {
                obj['whitelistEmails'] = ApiClient.convertToType(data['whitelistEmails'], ['String']);
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('profileImage')) {
                obj['profileImage'] = ApiClient.convertToType(data['profileImage'], 'String');
            }
            if (data.hasOwnProperty('suggestedQuestions')) {
                obj['suggestedQuestions'] = ApiClient.convertToType(data['suggestedQuestions'], ['String']);
            }
            if (data.hasOwnProperty('llm')) {
                obj['llm'] = V1ReplicasGet200ResponseItemsInnerLlm.constructFromObject(data['llm']);
            }
            if (data.hasOwnProperty('voicePreviewText')) {
                obj['voicePreviewText'] = ApiClient.convertToType(data['voicePreviewText'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['purpose'] && !(typeof data['purpose'] === 'string' || data['purpose'] instanceof String)) {
            throw new Error("Expected the field `purpose` to be a primitive type in the JSON string but got " + data['purpose']);
        }
        // ensure the json data is a string
        if (data['shortDescription'] && !(typeof data['shortDescription'] === 'string' || data['shortDescription'] instanceof String)) {
            throw new Error("Expected the field `shortDescription` to be a primitive type in the JSON string but got " + data['shortDescription']);
        }
        // ensure the json data is a string
        if (data['greeting'] && !(typeof data['greeting'] === 'string' || data['greeting'] instanceof String)) {
            throw new Error("Expected the field `greeting` to be a primitive type in the JSON string but got " + data['greeting']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['ownerID'] && !(typeof data['ownerID'] === 'string' || data['ownerID'] instanceof String)) {
            throw new Error("Expected the field `ownerID` to be a primitive type in the JSON string but got " + data['ownerID']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['whitelistEmails'])) {
            throw new Error("Expected the field `whitelistEmails` to be an array in the JSON data but got " + data['whitelistEmails']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // ensure the json data is a string
        if (data['profileImage'] && !(typeof data['profileImage'] === 'string' || data['profileImage'] instanceof String)) {
            throw new Error("Expected the field `profileImage` to be a primitive type in the JSON string but got " + data['profileImage']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['suggestedQuestions'])) {
            throw new Error("Expected the field `suggestedQuestions` to be an array in the JSON data but got " + data['suggestedQuestions']);
        }
        // validate the optional field `llm`
        if (data['llm']) { // data not null
          V1ReplicasGet200ResponseItemsInnerLlm.validateJSON(data['llm']);
        }
        // ensure the json data is a string
        if (data['voicePreviewText'] && !(typeof data['voicePreviewText'] === 'string' || data['voicePreviewText'] instanceof String)) {
            throw new Error("Expected the field `voicePreviewText` to be a primitive type in the JSON string but got " + data['voicePreviewText']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDGet200Response.RequiredProperties = ["name", "shortDescription", "greeting", "ownerID", "slug", "llm", "uuid"];

/**
 * The name of the replica.
 * @member {String} name
 */
V1ReplicasReplicaUUIDGet200Response.prototype['name'] = undefined;

/**
 * The purpose of the replica. This field is not used for training the replica.
 * @member {String} purpose
 */
V1ReplicasReplicaUUIDGet200Response.prototype['purpose'] = undefined;

/**
 * A short description of your replica. This field is not used for training the replica.
 * @member {String} shortDescription
 */
V1ReplicasReplicaUUIDGet200Response.prototype['shortDescription'] = undefined;

/**
 * The first thing your replica will say when you start a conversation with them.
 * @member {String} greeting
 */
V1ReplicasReplicaUUIDGet200Response.prototype['greeting'] = undefined;

/**
 * The replica type. `individual`: A replica of yourself. `character`: A replica of a character: can be anything you want. `brand`: A replica of a business persona or organization. 
 * @member {module:model/V1ReplicasReplicaUUIDGet200Response.TypeEnum} type
 * @default 'character'
 */
V1ReplicasReplicaUUIDGet200Response.prototype['type'] = 'character';

/**
 * The replica owner ID.
 * @member {String} ownerID
 */
V1ReplicasReplicaUUIDGet200Response.prototype['ownerID'] = undefined;

/**
 * Visibility of the replica. When set to `true`, only the owner will be able to find the replica and chat with it.
 * @member {Boolean} private
 * @default false
 */
V1ReplicasReplicaUUIDGet200Response.prototype['private'] = false;

/**
 * Emails of users who can use the replica.
 * @member {Array.<String>} whitelistEmails
 */
V1ReplicasReplicaUUIDGet200Response.prototype['whitelistEmails'] = undefined;

/**
 * The slug of the replica. Slugs can be used by API consumers to determine the URLs where replicas can be found.
 * @member {String} slug
 */
V1ReplicasReplicaUUIDGet200Response.prototype['slug'] = undefined;

/**
 * The tags associated with the replica. Tags help categorize replicas and make them easier to find.
 * @member {Array.<String>} tags
 */
V1ReplicasReplicaUUIDGet200Response.prototype['tags'] = undefined;

/**
 * The URL of the profile image of the replica. The image will be downloaded, optimized and stored on our servers, so the URL in the response will be different. Supported formats: .jpg, .jpeg, .png, .bmp, .webp, .avif
 * @member {String} profileImage
 * @default 'https://sensay.io/assets/default-replica-profile.webp'
 */
V1ReplicasReplicaUUIDGet200Response.prototype['profileImage'] = 'https://sensay.io/assets/default-replica-profile.webp';

/**
 * Suggested questions when starting a conversation.
 * @member {Array.<String>} suggestedQuestions
 */
V1ReplicasReplicaUUIDGet200Response.prototype['suggestedQuestions'] = undefined;

/**
 * @member {module:model/V1ReplicasGet200ResponseItemsInnerLlm} llm
 */
V1ReplicasReplicaUUIDGet200Response.prototype['llm'] = undefined;

/**
 * Text that can be used to generate a voice preview.
 * @member {String} voicePreviewText
 */
V1ReplicasReplicaUUIDGet200Response.prototype['voicePreviewText'] = undefined;

/**
 * The replica UUID
 * @member {String} uuid
 */
V1ReplicasReplicaUUIDGet200Response.prototype['uuid'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasReplicaUUIDGet200Response['TypeEnum'] = {

    /**
     * value: "individual"
     * @const
     */
    "individual": "individual",

    /**
     * value: "character"
     * @const
     */
    "character": "character",

    /**
     * value: "brand"
     * @const
     */
    "brand": "brand"
};



export default V1ReplicasReplicaUUIDGet200Response;

