/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner model module.
 * @module model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner</code>.
     * @alias module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner
     * @param id {Number} The ID of the source
     * @param score {Number} Relevance score of the source
     * @param status {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.StatusEnum} If the source has ever been scored or not
     * @param createdAt {Date} When the source was created
     * @param name {String} The name of the source
     * @param content {String} The actual content retrieved from the source
     */
    constructor(id, score, status, createdAt, name, content) { 
        
        V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.initialize(this, id, score, status, createdAt, name, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, score, status, createdAt, name, content) { 
        obj['id'] = id;
        obj['score'] = score;
        obj['status'] = status;
        obj['created_at'] = createdAt;
        obj['name'] = name;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner} The populated <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.RequiredProperties = ["id", "score", "status", "created_at", "name", "content"];

/**
 * The ID of the source
 * @member {Number} id
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.prototype['id'] = undefined;

/**
 * Relevance score of the source
 * @member {Number} score
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.prototype['score'] = undefined;

/**
 * If the source has ever been scored or not
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.StatusEnum} status
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.prototype['status'] = undefined;

/**
 * When the source was created
 * @member {Date} created_at
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.prototype['created_at'] = undefined;

/**
 * The name of the source
 * @member {String} name
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.prototype['name'] = undefined;

/**
 * The actual content retrieved from the source
 * @member {String} content
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.prototype['content'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner['StatusEnum'] = {

    /**
     * value: "scored"
     * @const
     */
    "scored": "scored",

    /**
     * value: "unscored"
     * @const
     */
    "unscored": "unscored"
};



export default V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner;

