/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException from './V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException';

/**
 * The V1ReplicasReplicaUUIDTrainingPost500Response model module.
 * @module model/V1ReplicasReplicaUUIDTrainingPost500Response
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDTrainingPost500Response {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDTrainingPost500Response</code>.
     * @alias module:model/V1ReplicasReplicaUUIDTrainingPost500Response
     * @param success {Boolean} Indicates the status of the request
     * @param error {String} A text representation of the error
     * @param requestId {String} A unique identifier of the request, useful for reporting
     */
    constructor(success, error, requestId) { 
        
        V1ReplicasReplicaUUIDTrainingPost500Response.initialize(this, success, error, requestId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, error, requestId) { 
        obj['success'] = success;
        obj['error'] = error;
        obj['request_id'] = requestId;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDTrainingPost500Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingPost500Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDTrainingPost500Response} The populated <code>V1ReplicasReplicaUUIDTrainingPost500Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDTrainingPost500Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('fingerprint')) {
                obj['fingerprint'] = ApiClient.convertToType(data['fingerprint'], 'String');
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
            if (data.hasOwnProperty('inner_exception')) {
                obj['inner_exception'] = V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.constructFromObject(data['inner_exception']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDTrainingPost500Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDTrainingPost500Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDTrainingPost500Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is a string
        if (data['fingerprint'] && !(typeof data['fingerprint'] === 'string' || data['fingerprint'] instanceof String)) {
            throw new Error("Expected the field `fingerprint` to be a primitive type in the JSON string but got " + data['fingerprint']);
        }
        // ensure the json data is a string
        if (data['request_id'] && !(typeof data['request_id'] === 'string' || data['request_id'] instanceof String)) {
            throw new Error("Expected the field `request_id` to be a primitive type in the JSON string but got " + data['request_id']);
        }
        // validate the optional field `inner_exception`
        if (data['inner_exception']) { // data not null
          V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.validateJSON(data['inner_exception']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDTrainingPost500Response.RequiredProperties = ["success", "error", "request_id"];

/**
 * Indicates the status of the request
 * @member {Boolean} success
 */
V1ReplicasReplicaUUIDTrainingPost500Response.prototype['success'] = undefined;

/**
 * A text representation of the error
 * @member {String} error
 */
V1ReplicasReplicaUUIDTrainingPost500Response.prototype['error'] = undefined;

/**
 * A unique identifier of the event, useful for reporting
 * @member {String} fingerprint
 */
V1ReplicasReplicaUUIDTrainingPost500Response.prototype['fingerprint'] = undefined;

/**
 * A unique identifier of the request, useful for reporting
 * @member {String} request_id
 */
V1ReplicasReplicaUUIDTrainingPost500Response.prototype['request_id'] = undefined;

/**
 * @member {module:model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException} inner_exception
 */
V1ReplicasReplicaUUIDTrainingPost500Response.prototype['inner_exception'] = undefined;






export default V1ReplicasReplicaUUIDTrainingPost500Response;

