/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasGet200ResponseItemsInnerTelegramIntegration model module.
 * @module model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration
 * @version 2025-03-25
 */
class V1ReplicasGet200ResponseItemsInnerTelegramIntegration {
    /**
     * Constructs a new <code>V1ReplicasGet200ResponseItemsInnerTelegramIntegration</code>.
     * The Telegram integration of the replica.
     * @alias module:model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration
     * @param token {String} 
     * @param serviceName {String} 
     */
    constructor(token, serviceName) { 
        
        V1ReplicasGet200ResponseItemsInnerTelegramIntegration.initialize(this, token, serviceName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token, serviceName) { 
        obj['token'] = token;
        obj['service_name'] = serviceName;
    }

    /**
     * Constructs a <code>V1ReplicasGet200ResponseItemsInnerTelegramIntegration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration} obj Optional instance to populate.
     * @return {module:model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration} The populated <code>V1ReplicasGet200ResponseItemsInnerTelegramIntegration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasGet200ResponseItemsInnerTelegramIntegration();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('service_name')) {
                obj['service_name'] = ApiClient.convertToType(data['service_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasGet200ResponseItemsInnerTelegramIntegration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasGet200ResponseItemsInnerTelegramIntegration</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasGet200ResponseItemsInnerTelegramIntegration.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['service_name'] && !(typeof data['service_name'] === 'string' || data['service_name'] instanceof String)) {
            throw new Error("Expected the field `service_name` to be a primitive type in the JSON string but got " + data['service_name']);
        }

        return true;
    }


}

V1ReplicasGet200ResponseItemsInnerTelegramIntegration.RequiredProperties = ["token", "service_name"];

/**
 * @member {String} token
 */
V1ReplicasGet200ResponseItemsInnerTelegramIntegration.prototype['token'] = undefined;

/**
 * @member {String} service_name
 */
V1ReplicasGet200ResponseItemsInnerTelegramIntegration.prototype['service_name'] = undefined;






export default V1ReplicasGet200ResponseItemsInnerTelegramIntegration;

