/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDTrainingPost200Response model module.
 * @module model/V1ReplicasReplicaUUIDTrainingPost200Response
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDTrainingPost200Response {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDTrainingPost200Response</code>.
     * @alias module:model/V1ReplicasReplicaUUIDTrainingPost200Response
     * @param success {Boolean} Indicates if the knowledge base entry was created successfully
     * @param knowledgeBaseID {Number} The unique identifier for the newly created knowledge base entry. You'll need this ID for subsequent operations like adding content via the Update endpoint.
     */
    constructor(success, knowledgeBaseID) { 
        
        V1ReplicasReplicaUUIDTrainingPost200Response.initialize(this, success, knowledgeBaseID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, knowledgeBaseID) { 
        obj['success'] = success;
        obj['knowledgeBaseID'] = knowledgeBaseID;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDTrainingPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingPost200Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDTrainingPost200Response} The populated <code>V1ReplicasReplicaUUIDTrainingPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDTrainingPost200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('knowledgeBaseID')) {
                obj['knowledgeBaseID'] = ApiClient.convertToType(data['knowledgeBaseID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDTrainingPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDTrainingPost200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDTrainingPost200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

V1ReplicasReplicaUUIDTrainingPost200Response.RequiredProperties = ["success", "knowledgeBaseID"];

/**
 * Indicates if the knowledge base entry was created successfully
 * @member {Boolean} success
 */
V1ReplicasReplicaUUIDTrainingPost200Response.prototype['success'] = undefined;

/**
 * The unique identifier for the newly created knowledge base entry. You'll need this ID for subsequent operations like adding content via the Update endpoint.
 * @member {Number} knowledgeBaseID
 */
V1ReplicasReplicaUUIDTrainingPost200Response.prototype['knowledgeBaseID'] = undefined;






export default V1ReplicasReplicaUUIDTrainingPost200Response;

