/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData model module.
 * @module model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData</code>.
     * Telegram information about the message
     * @alias module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData
     * @extends Object
     * @param chatType {String} Type of the chat, can be either `private`, `group`, `supergroup` or `channel`.
     * @param chatId {Number} Unique identifier for this chat.
     * @param messageId {Number} Unique message identifier inside this chat. In specific instances (e.g., message containing a video sent to a big chat).
     */
    constructor(chatType, chatId, messageId) { 
        
        V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.initialize(this, chatType, chatId, messageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chatType, chatId, messageId) { 
        obj['chat_type'] = chatType;
        obj['chat_id'] = chatId;
        obj['message_id'] = messageId;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData} The populated <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('chat_type')) {
                obj['chat_type'] = ApiClient.convertToType(data['chat_type'], 'String');
            }
            if (data.hasOwnProperty('chat_id')) {
                obj['chat_id'] = ApiClient.convertToType(data['chat_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('message_id')) {
                obj['message_id'] = ApiClient.convertToType(data['message_id'], 'Number');
            }
            if (data.hasOwnProperty('message_thread_id')) {
                obj['message_thread_id'] = ApiClient.convertToType(data['message_thread_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['chat_type'] && !(typeof data['chat_type'] === 'string' || data['chat_type'] instanceof String)) {
            throw new Error("Expected the field `chat_type` to be a primitive type in the JSON string but got " + data['chat_type']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.RequiredProperties = ["chat_type", "chat_id", "message_id"];

/**
 * Type of the chat, can be either `private`, `group`, `supergroup` or `channel`.
 * @member {String} chat_type
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.prototype['chat_type'] = undefined;

/**
 * Unique identifier for this chat.
 * @member {Number} chat_id
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.prototype['chat_id'] = undefined;

/**
 * Sender of the message's userID; may be empty for messages sent to channels. For backward compatibility, if the message was sent on behalf of a chat, the field contains a fake sender user in non-channel chats.
 * @member {Number} user_id
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.prototype['user_id'] = undefined;

/**
 * Sender of the message's username; may be empty for messages sent to channels. For backward compatibility, if the message was sent on behalf of a chat, the field contains a fake sender user in non-channel chats.
 * @member {String} username
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.prototype['username'] = undefined;

/**
 * Unique message identifier inside this chat. In specific instances (e.g., message containing a video sent to a big chat).
 * @member {Number} message_id
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.prototype['message_id'] = undefined;

/**
 * Unique identifier of a message thread or a forum topic to which the message belongs; for supergroups only.
 * @member {Number} message_thread_id
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.prototype['message_thread_id'] = undefined;






export default V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData;

