/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response model module.
 * @module model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response</code>.
     * @alias module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response
     * @param success {Boolean} Indicates the status of the request
     * @param id {Number} 
     */
    constructor(success, id) { 
        
        V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response.initialize(this, success, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, id) { 
        obj['success'] = success;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response} The populated <code>V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response.RequiredProperties = ["success", "id"];

/**
 * Indicates the status of the request
 * @member {Boolean} success
 */
V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response.prototype['success'] = undefined;

/**
 * @member {Number} id
 */
V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response.prototype['id'] = undefined;






export default V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response;

