/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData from './V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData';

/**
 * The V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest model module.
 * @module model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest</code>.
     * @alias module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest
     * @extends Object
     * @param content {String} Content of the message
     * @param telegramData {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData} 
     */
    constructor(content, telegramData) { 
        
        V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest.initialize(this, content, telegramData);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, telegramData) { 
        obj['content'] = content;
        obj['telegram_data'] = telegramData;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest} The populated <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('telegram_data')) {
                obj['telegram_data'] = V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.constructFromObject(data['telegram_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest.RequiredProperties = ["content", "telegram_data"];

/**
 * Content of the message
 * @member {String} content
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest.prototype['content'] = undefined;

/**
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData} telegram_data
 */
V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest.prototype['telegram_data'] = undefined;






export default V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest;

