/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData model module.
 * @module model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData</code>.
     * Discord information about the message
     * @alias module:model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData
     * @extends Object
     * @param channelId {String} Channel ID
     * @param channelName {String} Channel name
     * @param authorId {String} Author ID
     * @param authorName {String} Author name
     * @param messageId {String} Message ID
     */
    constructor(channelId, channelName, authorId, authorName, messageId) { 
        
        V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.initialize(this, channelId, channelName, authorId, authorName, messageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, channelId, channelName, authorId, authorName, messageId) { 
        obj['channel_id'] = channelId;
        obj['channel_name'] = channelName;
        obj['author_id'] = authorId;
        obj['author_name'] = authorName;
        obj['message_id'] = messageId;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData} The populated <code>V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('channel_id')) {
                obj['channel_id'] = ApiClient.convertToType(data['channel_id'], 'String');
            }
            if (data.hasOwnProperty('channel_name')) {
                obj['channel_name'] = ApiClient.convertToType(data['channel_name'], 'String');
            }
            if (data.hasOwnProperty('author_id')) {
                obj['author_id'] = ApiClient.convertToType(data['author_id'], 'String');
            }
            if (data.hasOwnProperty('author_name')) {
                obj['author_name'] = ApiClient.convertToType(data['author_name'], 'String');
            }
            if (data.hasOwnProperty('message_id')) {
                obj['message_id'] = ApiClient.convertToType(data['message_id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('server_id')) {
                obj['server_id'] = ApiClient.convertToType(data['server_id'], 'String');
            }
            if (data.hasOwnProperty('server_name')) {
                obj['server_name'] = ApiClient.convertToType(data['server_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['channel_id'] && !(typeof data['channel_id'] === 'string' || data['channel_id'] instanceof String)) {
            throw new Error("Expected the field `channel_id` to be a primitive type in the JSON string but got " + data['channel_id']);
        }
        // ensure the json data is a string
        if (data['channel_name'] && !(typeof data['channel_name'] === 'string' || data['channel_name'] instanceof String)) {
            throw new Error("Expected the field `channel_name` to be a primitive type in the JSON string but got " + data['channel_name']);
        }
        // ensure the json data is a string
        if (data['author_id'] && !(typeof data['author_id'] === 'string' || data['author_id'] instanceof String)) {
            throw new Error("Expected the field `author_id` to be a primitive type in the JSON string but got " + data['author_id']);
        }
        // ensure the json data is a string
        if (data['author_name'] && !(typeof data['author_name'] === 'string' || data['author_name'] instanceof String)) {
            throw new Error("Expected the field `author_name` to be a primitive type in the JSON string but got " + data['author_name']);
        }
        // ensure the json data is a string
        if (data['message_id'] && !(typeof data['message_id'] === 'string' || data['message_id'] instanceof String)) {
            throw new Error("Expected the field `message_id` to be a primitive type in the JSON string but got " + data['message_id']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['server_id'] && !(typeof data['server_id'] === 'string' || data['server_id'] instanceof String)) {
            throw new Error("Expected the field `server_id` to be a primitive type in the JSON string but got " + data['server_id']);
        }
        // ensure the json data is a string
        if (data['server_name'] && !(typeof data['server_name'] === 'string' || data['server_name'] instanceof String)) {
            throw new Error("Expected the field `server_name` to be a primitive type in the JSON string but got " + data['server_name']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.RequiredProperties = ["channel_id", "channel_name", "author_id", "author_name", "message_id"];

/**
 * Channel ID
 * @member {String} channel_id
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['channel_id'] = undefined;

/**
 * Channel name
 * @member {String} channel_name
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['channel_name'] = undefined;

/**
 * Author ID
 * @member {String} author_id
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['author_id'] = undefined;

/**
 * Author name
 * @member {String} author_name
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['author_name'] = undefined;

/**
 * Message ID
 * @member {String} message_id
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['message_id'] = undefined;

/**
 * Message creation timestamp
 * @member {String} created_at
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['created_at'] = undefined;

/**
 * Server ID
 * @member {String} server_id
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['server_id'] = undefined;

/**
 * Server name
 * @member {String} server_name
 */
V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.prototype['server_name'] = undefined;






export default V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData;

