/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasGet200ResponseItemsInnerLlm model module.
 * @module model/V1ReplicasGet200ResponseItemsInnerLlm
 * @version 2025-03-25
 */
class V1ReplicasGet200ResponseItemsInnerLlm {
    /**
     * Constructs a new <code>V1ReplicasGet200ResponseItemsInnerLlm</code>.
     * @alias module:model/V1ReplicasGet200ResponseItemsInnerLlm
     */
    constructor() { 
        
        V1ReplicasGet200ResponseItemsInnerLlm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['model'] = 'claude-3-5-haiku-latest';
        obj['memoryMode'] = 'rag-search';
    }

    /**
     * Constructs a <code>V1ReplicasGet200ResponseItemsInnerLlm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasGet200ResponseItemsInnerLlm} obj Optional instance to populate.
     * @return {module:model/V1ReplicasGet200ResponseItemsInnerLlm} The populated <code>V1ReplicasGet200ResponseItemsInnerLlm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasGet200ResponseItemsInnerLlm();

            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('memoryMode')) {
                obj['memoryMode'] = ApiClient.convertToType(data['memoryMode'], 'String');
            }
            if (data.hasOwnProperty('systemMessage')) {
                obj['systemMessage'] = ApiClient.convertToType(data['systemMessage'], 'String');
            }
            if (data.hasOwnProperty('tools')) {
                obj['tools'] = ApiClient.convertToType(data['tools'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasGet200ResponseItemsInnerLlm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasGet200ResponseItemsInnerLlm</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['memoryMode'] && !(typeof data['memoryMode'] === 'string' || data['memoryMode'] instanceof String)) {
            throw new Error("Expected the field `memoryMode` to be a primitive type in the JSON string but got " + data['memoryMode']);
        }
        // ensure the json data is a string
        if (data['systemMessage'] && !(typeof data['systemMessage'] === 'string' || data['systemMessage'] instanceof String)) {
            throw new Error("Expected the field `systemMessage` to be a primitive type in the JSON string but got " + data['systemMessage']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tools'])) {
            throw new Error("Expected the field `tools` to be an array in the JSON data but got " + data['tools']);
        }

        return true;
    }


}



/**
 * The LLM model of the replica.
 * @member {module:model/V1ReplicasGet200ResponseItemsInnerLlm.ModelEnum} model
 * @default 'claude-3-5-haiku-latest'
 */
V1ReplicasGet200ResponseItemsInnerLlm.prototype['model'] = 'claude-3-5-haiku-latest';

/**
 * The memory mode of the replica.
 * @member {module:model/V1ReplicasGet200ResponseItemsInnerLlm.MemoryModeEnum} memoryMode
 * @default 'rag-search'
 */
V1ReplicasGet200ResponseItemsInnerLlm.prototype['memoryMode'] = 'rag-search';

/**
 * Who is your replica? How do you want it to talk, respond and act.
 * @member {String} systemMessage
 */
V1ReplicasGet200ResponseItemsInnerLlm.prototype['systemMessage'] = undefined;

/**
 * The replica's tools. Tools enable agents to interact with the world. `getTokenInfo`: Allows replica to get token information 
 * @member {Array.<module:model/V1ReplicasGet200ResponseItemsInnerLlm.ToolsEnum>} tools
 */
V1ReplicasGet200ResponseItemsInnerLlm.prototype['tools'] = undefined;





/**
 * Allowed values for the <code>model</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasGet200ResponseItemsInnerLlm['ModelEnum'] = {

    /**
     * value: "gpt-4o"
     * @const
     */
    "gpt-4o": "gpt-4o",

    /**
     * value: "claude-3-5-haiku-latest"
     * @const
     */
    "claude-3-5-haiku-latest": "claude-3-5-haiku-latest",

    /**
     * value: "claude-3-7-sonnet-latest"
     * @const
     */
    "claude-3-7-sonnet-latest": "claude-3-7-sonnet-latest",

    /**
     * value: "grok-2-latest"
     * @const
     */
    "grok-2-latest": "grok-2-latest",

    /**
     * value: "grok-3-beta"
     * @const
     */
    "grok-3-beta": "grok-3-beta",

    /**
     * value: "deepseek-chat"
     * @const
     */
    "deepseek-chat": "deepseek-chat",

    /**
     * value: "o3-mini"
     * @const
     */
    "o3-mini": "o3-mini",

    /**
     * value: "gpt-4o-mini"
     * @const
     */
    "gpt-4o-mini": "gpt-4o-mini",

    /**
     * value: "huggingface-eva"
     * @const
     */
    "huggingface-eva": "huggingface-eva",

    /**
     * value: "huggingface-dolphin-llama"
     * @const
     */
    "huggingface-dolphin-llama": "huggingface-dolphin-llama"
};


/**
 * Allowed values for the <code>memoryMode</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasGet200ResponseItemsInnerLlm['MemoryModeEnum'] = {

    /**
     * value: "prompt-caching"
     * @const
     */
    "prompt-caching": "prompt-caching",

    /**
     * value: "rag-search"
     * @const
     */
    "rag-search": "rag-search"
};


/**
 * Allowed values for the <code>tools</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasGet200ResponseItemsInnerLlm['ToolsEnum'] = {

    /**
     * value: "getTokenInfo"
     * @const
     */
    "getTokenInfo": "getTokenInfo",

    /**
     * value: "getUdaoTokenInfo"
     * @const
     */
    "getUdaoTokenInfo": "getUdaoTokenInfo",

    /**
     * value: "getSensayTokenInfo"
     * @const
     */
    "getSensayTokenInfo": "getSensayTokenInfo",

    /**
     * value: "getTokenInfoMEAI"
     * @const
     */
    "getTokenInfoMEAI": "getTokenInfoMEAI",

    /**
     * value: "answerToLife"
     * @const
     */
    "answerToLife": "answerToLife",

    /**
     * value: "toolhouse"
     * @const
     */
    "toolhouse": "toolhouse"
};



export default V1ReplicasGet200ResponseItemsInnerLlm;

