/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response model module.
 * @module model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response</code>.
     * @alias module:model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response
     * @param success {Boolean} Indicates the status of the request
     * @param message {String} The reason why the operation is accepted instead of returning an immediate success.
     */
    constructor(success, message) { 
        
        V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response.initialize(this, success, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, message) { 
        obj['success'] = success;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response} The populated <code>V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response.RequiredProperties = ["success", "message"];

/**
 * Indicates the status of the request
 * @member {Boolean} success
 */
V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response.prototype['success'] = undefined;

/**
 * The reason why the operation is accepted instead of returning an immediate success.
 * @member {String} message
 */
V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response.prototype['message'] = undefined;






export default V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response;

