/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner from './V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner';

/**
 * The V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner model module.
 * @module model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner</code>.
     * @alias module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner
     * @param content {String} The content of the message
     * @param createdAt {Date} The date and time the message was created
     * @param id {Number} The ID of the message
     * @param isPrivate {Boolean} Whether the replica is private
     * @param role {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.RoleEnum} The role of the message
     * @param source {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.SourceEnum} From which platform is message was sent from
     * @param sources {Array.<module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner>} The sources of information used to create the response via RAG (Retrieval-Augmented Generation)
     * @param userUuid {String} The UUID of the user
     * @param originalMessageId {String} The ID of the message from the LLM. Present when role is assistant. Will be removed in the future.
     */
    constructor(content, createdAt, id, isPrivate, role, source, sources, userUuid, originalMessageId) { 
        
        V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.initialize(this, content, createdAt, id, isPrivate, role, source, sources, userUuid, originalMessageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, createdAt, id, isPrivate, role, source, sources, userUuid, originalMessageId) { 
        obj['content'] = content;
        obj['created_at'] = createdAt;
        obj['id'] = id;
        obj['is_private'] = isPrivate;
        obj['role'] = role;
        obj['source'] = source;
        obj['sources'] = sources;
        obj['user_uuid'] = userUuid;
        obj['original_message_id'] = originalMessageId;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner} The populated <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('is_private')) {
                obj['is_private'] = ApiClient.convertToType(data['is_private'], 'Boolean');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner]);
            }
            if (data.hasOwnProperty('user_uuid')) {
                obj['user_uuid'] = ApiClient.convertToType(data['user_uuid'], 'String');
            }
            if (data.hasOwnProperty('original_message_id')) {
                obj['original_message_id'] = ApiClient.convertToType(data['original_message_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
            throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
        }
        if (data['sources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sources'])) {
                throw new Error("Expected the field `sources` to be an array in the JSON data but got " + data['sources']);
            }
            // validate the optional field `sources` (array)
            for (const item of data['sources']) {
                V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['user_uuid'] && !(typeof data['user_uuid'] === 'string' || data['user_uuid'] instanceof String)) {
            throw new Error("Expected the field `user_uuid` to be a primitive type in the JSON string but got " + data['user_uuid']);
        }
        // ensure the json data is a string
        if (data['original_message_id'] && !(typeof data['original_message_id'] === 'string' || data['original_message_id'] instanceof String)) {
            throw new Error("Expected the field `original_message_id` to be a primitive type in the JSON string but got " + data['original_message_id']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.RequiredProperties = ["content", "created_at", "id", "is_private", "role", "source", "sources", "user_uuid", "original_message_id"];

/**
 * The content of the message
 * @member {String} content
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['content'] = undefined;

/**
 * The date and time the message was created
 * @member {Date} created_at
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['created_at'] = undefined;

/**
 * The ID of the message
 * @member {Number} id
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['id'] = undefined;

/**
 * Whether the replica is private
 * @member {Boolean} is_private
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['is_private'] = undefined;

/**
 * The role of the message
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.RoleEnum} role
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['role'] = undefined;

/**
 * From which platform is message was sent from
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.SourceEnum} source
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['source'] = undefined;

/**
 * The sources of information used to create the response via RAG (Retrieval-Augmented Generation)
 * @member {Array.<module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner>} sources
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['sources'] = undefined;

/**
 * The UUID of the user
 * @member {String} user_uuid
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['user_uuid'] = undefined;

/**
 * The ID of the message from the LLM. Present when role is assistant. Will be removed in the future.
 * @member {String} original_message_id
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.prototype['original_message_id'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner['RoleEnum'] = {

    /**
     * value: "user"
     * @const
     */
    "user": "user",

    /**
     * value: "assistant"
     * @const
     */
    "assistant": "assistant"
};


/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner['SourceEnum'] = {

    /**
     * value: "discord"
     * @const
     */
    "discord": "discord",

    /**
     * value: "telegram"
     * @const
     */
    "telegram": "telegram",

    /**
     * value: "embed"
     * @const
     */
    "embed": "embed",

    /**
     * value: "web"
     * @const
     */
    "web": "web",

    /**
     * value: "telegram_autopilot"
     * @const
     */
    "telegram_autopilot": "telegram_autopilot"
};



export default V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner;

