/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData from './V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData';

/**
 * The V1ReplicasReplicaUUIDChatCompletionsPostRequest model module.
 * @module model/V1ReplicasReplicaUUIDChatCompletionsPostRequest
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatCompletionsPostRequest {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatCompletionsPostRequest</code>.
     * @alias module:model/V1ReplicasReplicaUUIDChatCompletionsPostRequest
     * @extends Object
     * @param content {String} The prompt to generate completions for, encoded as a string.
     */
    constructor(content) { 
        
        V1ReplicasReplicaUUIDChatCompletionsPostRequest.initialize(this, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content) { 
        obj['content'] = content;
        obj['skip_chat_history'] = false;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatCompletionsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatCompletionsPostRequest} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatCompletionsPostRequest} The populated <code>V1ReplicasReplicaUUIDChatCompletionsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatCompletionsPostRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('skip_chat_history')) {
                obj['skip_chat_history'] = ApiClient.convertToType(data['skip_chat_history'], 'Boolean');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('discord_data')) {
                obj['discord_data'] = V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData.constructFromObject(data['discord_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatCompletionsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatCompletionsPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatCompletionsPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
            throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatCompletionsPostRequest.RequiredProperties = ["content"];

/**
 * The prompt to generate completions for, encoded as a string.
 * @member {String} content
 */
V1ReplicasReplicaUUIDChatCompletionsPostRequest.prototype['content'] = undefined;

/**
 * When set to true, historical messages are not used in the context, and the message is not appended to the conversation history, thus it is excluded from all future chat context.
 * @member {Boolean} skip_chat_history
 * @default false
 */
V1ReplicasReplicaUUIDChatCompletionsPostRequest.prototype['skip_chat_history'] = false;

/**
 * The place where the conversation is happening, which informs where the message should be saved in the chat history.
 * @member {module:model/V1ReplicasReplicaUUIDChatCompletionsPostRequest.SourceEnum} source
 */
V1ReplicasReplicaUUIDChatCompletionsPostRequest.prototype['source'] = undefined;

/**
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData} discord_data
 */
V1ReplicasReplicaUUIDChatCompletionsPostRequest.prototype['discord_data'] = undefined;





/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasReplicaUUIDChatCompletionsPostRequest['SourceEnum'] = {

    /**
     * value: "discord"
     * @const
     */
    "discord": "discord",

    /**
     * value: "telegram"
     * @const
     */
    "telegram": "telegram",

    /**
     * value: "embed"
     * @const
     */
    "embed": "embed",

    /**
     * value: "web"
     * @const
     */
    "web": "web",

    /**
     * value: "telegram_autopilot"
     * @const
     */
    "telegram_autopilot": "telegram_autopilot"
};



export default V1ReplicasReplicaUUIDChatCompletionsPostRequest;

