/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest model module.
 * @module model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest</code>.
     * @alias module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest
     * @extends Object
     * @param telegramToken {String} Telegram Bot ID
     * @param mention {String} Telegram Bot Name
     */
    constructor(telegramToken, mention) { 
        
        V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest.initialize(this, telegramToken, mention);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, telegramToken, mention) { 
        obj['telegram_token'] = telegramToken;
        obj['mention'] = mention;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest} The populated <code>V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('telegram_token')) {
                obj['telegram_token'] = ApiClient.convertToType(data['telegram_token'], 'String');
            }
            if (data.hasOwnProperty('mention')) {
                obj['mention'] = ApiClient.convertToType(data['mention'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['telegram_token'] && !(typeof data['telegram_token'] === 'string' || data['telegram_token'] instanceof String)) {
            throw new Error("Expected the field `telegram_token` to be a primitive type in the JSON string but got " + data['telegram_token']);
        }
        // ensure the json data is a string
        if (data['mention'] && !(typeof data['mention'] === 'string' || data['mention'] instanceof String)) {
            throw new Error("Expected the field `mention` to be a primitive type in the JSON string but got " + data['mention']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest.RequiredProperties = ["telegram_token", "mention"];

/**
 * Telegram Bot ID
 * @member {String} telegram_token
 */
V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest.prototype['telegram_token'] = undefined;

/**
 * Telegram Bot Name
 * @member {String} mention
 */
V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest.prototype['mention'] = undefined;






export default V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest;

