/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner from './V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner';

/**
 * The V1ReplicasReplicaUUIDChatHistoryGet200Response model module.
 * @module model/V1ReplicasReplicaUUIDChatHistoryGet200Response
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatHistoryGet200Response {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatHistoryGet200Response</code>.
     * @alias module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response
     * @param success {Boolean} Indicates the status of the request
     * @param type {String} 
     */
    constructor(success, type) { 
        
        V1ReplicasReplicaUUIDChatHistoryGet200Response.initialize(this, success, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, type) { 
        obj['success'] = success;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatHistoryGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response} The populated <code>V1ReplicasReplicaUUIDChatHistoryGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatHistoryGet200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatHistoryGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatHistoryGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatHistoryGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner.validateJSON(item);
            };
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatHistoryGet200Response.RequiredProperties = ["success", "type"];

/**
 * Indicates the status of the request
 * @member {Boolean} success
 */
V1ReplicasReplicaUUIDChatHistoryGet200Response.prototype['success'] = undefined;

/**
 * @member {String} type
 */
V1ReplicasReplicaUUIDChatHistoryGet200Response.prototype['type'] = undefined;

/**
 * @member {Array.<module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner>} items
 */
V1ReplicasReplicaUUIDChatHistoryGet200Response.prototype['items'] = undefined;






export default V1ReplicasReplicaUUIDChatHistoryGet200Response;

