/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasGet200ResponseItemsInnerDiscordIntegration from './V1ReplicasGet200ResponseItemsInnerDiscordIntegration';
import V1ReplicasGet200ResponseItemsInnerLlm from './V1ReplicasGet200ResponseItemsInnerLlm';
import V1ReplicasGet200ResponseItemsInnerTelegramIntegration from './V1ReplicasGet200ResponseItemsInnerTelegramIntegration';

/**
 * The V1ReplicasGet200ResponseItemsInner model module.
 * @module model/V1ReplicasGet200ResponseItemsInner
 * @version 2025-03-25
 */
class V1ReplicasGet200ResponseItemsInner {
    /**
     * Constructs a new <code>V1ReplicasGet200ResponseItemsInner</code>.
     * @alias module:model/V1ReplicasGet200ResponseItemsInner
     * @extends Object
     * @param name {String} The name of the replica.
     * @param shortDescription {String} A short description of your replica. This field is not used for training the replica.
     * @param greeting {String} The first thing your replica will say when you start a conversation with them.
     * @param ownerID {String} The replica owner ID.
     * @param slug {String} The slug of the replica. Slugs can be used by API consumers to determine the URLs where replicas can be found.
     * @param llm {module:model/V1ReplicasGet200ResponseItemsInnerLlm} 
     * @param uuid {String} The replica UUID
     * @param profileImage {String} The URL of the profile image of the replica. Please use `profileImage` instead.
     * @param shortDescription {String} The description of the replica. Please use `shortDescription` instead.
     * @param introduction {String} The introduction of the replica. Please use `greeting` instead.
     * @param createdAt {Date} The date and time the replica was created.
     * @param ownerUuid {String} The UUID of the owner of the replica. Please migrate to the new User ID system and use `ownerID` instead.
     * @param voiceEnabled {Boolean} Whether the replica has voice support.
     * @param videoEnabled {Boolean} Whether the replica has video support.
     * @param chatHistoryCount {Number} The total number of chat history items related to this replica, for all users of the organization.
     * @param systemMessage {String} The replica's tone, personality and behaviour, Please use `llm.systemMessage` instead.
     * @param discordIntegration {module:model/V1ReplicasGet200ResponseItemsInnerDiscordIntegration} 
     * @param telegramIntegration {module:model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration} 
     */
    constructor(name, shortDescription, greeting, ownerID, slug, llm, uuid, profileImage, shortDescription2, introduction, createdAt, ownerUuid, voiceEnabled, videoEnabled, chatHistoryCount, systemMessage, discordIntegration, telegramIntegration) { 
        
        V1ReplicasGet200ResponseItemsInner.initialize(this, name, shortDescription, greeting, ownerID, slug, llm, uuid, profileImage, shortDescription2, introduction, createdAt, ownerUuid, voiceEnabled, videoEnabled, chatHistoryCount, systemMessage, discordIntegration, telegramIntegration);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, shortDescription, greeting, ownerID, slug, llm, uuid, profileImage, shortDescription2, introduction, createdAt, ownerUuid, voiceEnabled, videoEnabled, chatHistoryCount, systemMessage, discordIntegration, telegramIntegration) { 
        obj['name'] = name;
        obj['shortDescription'] = shortDescription;
        obj['greeting'] = greeting;
        obj['type'] = 'character';
        obj['ownerID'] = ownerID;
        obj['private'] = false;
        obj['slug'] = slug;
        obj['profileImage'] = 'https://sensay.io/assets/default-replica-profile.webp';
        obj['llm'] = llm;
        obj['uuid'] = uuid;
        obj['profile_image'] = profileImage;
        obj['short_description'] = shortDescription2;
        obj['introduction'] = introduction;
        obj['created_at'] = createdAt;
        obj['owner_uuid'] = ownerUuid;
        obj['voice_enabled'] = voiceEnabled;
        obj['video_enabled'] = videoEnabled;
        obj['chat_history_count'] = chatHistoryCount;
        obj['system_message'] = systemMessage;
        obj['discord_integration'] = discordIntegration;
        obj['telegram_integration'] = telegramIntegration;
    }

    /**
     * Constructs a <code>V1ReplicasGet200ResponseItemsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasGet200ResponseItemsInner} obj Optional instance to populate.
     * @return {module:model/V1ReplicasGet200ResponseItemsInner} The populated <code>V1ReplicasGet200ResponseItemsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasGet200ResponseItemsInner();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('purpose')) {
                obj['purpose'] = ApiClient.convertToType(data['purpose'], 'String');
            }
            if (data.hasOwnProperty('shortDescription')) {
                obj['shortDescription'] = ApiClient.convertToType(data['shortDescription'], 'String');
            }
            if (data.hasOwnProperty('greeting')) {
                obj['greeting'] = ApiClient.convertToType(data['greeting'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('ownerID')) {
                obj['ownerID'] = ApiClient.convertToType(data['ownerID'], 'String');
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
            if (data.hasOwnProperty('whitelistEmails')) {
                obj['whitelistEmails'] = ApiClient.convertToType(data['whitelistEmails'], ['String']);
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('profileImage')) {
                obj['profileImage'] = ApiClient.convertToType(data['profileImage'], 'String');
            }
            if (data.hasOwnProperty('suggestedQuestions')) {
                obj['suggestedQuestions'] = ApiClient.convertToType(data['suggestedQuestions'], ['String']);
            }
            if (data.hasOwnProperty('llm')) {
                obj['llm'] = V1ReplicasGet200ResponseItemsInnerLlm.constructFromObject(data['llm']);
            }
            if (data.hasOwnProperty('voicePreviewText')) {
                obj['voicePreviewText'] = ApiClient.convertToType(data['voicePreviewText'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('profile_image')) {
                obj['profile_image'] = ApiClient.convertToType(data['profile_image'], 'String');
            }
            if (data.hasOwnProperty('short_description')) {
                obj['short_description'] = ApiClient.convertToType(data['short_description'], 'String');
            }
            if (data.hasOwnProperty('introduction')) {
                obj['introduction'] = ApiClient.convertToType(data['introduction'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('owner_uuid')) {
                obj['owner_uuid'] = ApiClient.convertToType(data['owner_uuid'], 'String');
            }
            if (data.hasOwnProperty('voice_enabled')) {
                obj['voice_enabled'] = ApiClient.convertToType(data['voice_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('video_enabled')) {
                obj['video_enabled'] = ApiClient.convertToType(data['video_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('chat_history_count')) {
                obj['chat_history_count'] = ApiClient.convertToType(data['chat_history_count'], 'Number');
            }
            if (data.hasOwnProperty('system_message')) {
                obj['system_message'] = ApiClient.convertToType(data['system_message'], 'String');
            }
            if (data.hasOwnProperty('discord_integration')) {
                obj['discord_integration'] = V1ReplicasGet200ResponseItemsInnerDiscordIntegration.constructFromObject(data['discord_integration']);
            }
            if (data.hasOwnProperty('telegram_integration')) {
                obj['telegram_integration'] = V1ReplicasGet200ResponseItemsInnerTelegramIntegration.constructFromObject(data['telegram_integration']);
            }
            if (data.hasOwnProperty('elevenLabsID')) {
                obj['elevenLabsID'] = ApiClient.convertToType(data['elevenLabsID'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasGet200ResponseItemsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasGet200ResponseItemsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasGet200ResponseItemsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['purpose'] && !(typeof data['purpose'] === 'string' || data['purpose'] instanceof String)) {
            throw new Error("Expected the field `purpose` to be a primitive type in the JSON string but got " + data['purpose']);
        }
        // ensure the json data is a string
        if (data['shortDescription'] && !(typeof data['shortDescription'] === 'string' || data['shortDescription'] instanceof String)) {
            throw new Error("Expected the field `shortDescription` to be a primitive type in the JSON string but got " + data['shortDescription']);
        }
        // ensure the json data is a string
        if (data['greeting'] && !(typeof data['greeting'] === 'string' || data['greeting'] instanceof String)) {
            throw new Error("Expected the field `greeting` to be a primitive type in the JSON string but got " + data['greeting']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['ownerID'] && !(typeof data['ownerID'] === 'string' || data['ownerID'] instanceof String)) {
            throw new Error("Expected the field `ownerID` to be a primitive type in the JSON string but got " + data['ownerID']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['whitelistEmails'])) {
            throw new Error("Expected the field `whitelistEmails` to be an array in the JSON data but got " + data['whitelistEmails']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // ensure the json data is a string
        if (data['profileImage'] && !(typeof data['profileImage'] === 'string' || data['profileImage'] instanceof String)) {
            throw new Error("Expected the field `profileImage` to be a primitive type in the JSON string but got " + data['profileImage']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['suggestedQuestions'])) {
            throw new Error("Expected the field `suggestedQuestions` to be an array in the JSON data but got " + data['suggestedQuestions']);
        }
        // validate the optional field `llm`
        if (data['llm']) { // data not null
          V1ReplicasGet200ResponseItemsInnerLlm.validateJSON(data['llm']);
        }
        // ensure the json data is a string
        if (data['voicePreviewText'] && !(typeof data['voicePreviewText'] === 'string' || data['voicePreviewText'] instanceof String)) {
            throw new Error("Expected the field `voicePreviewText` to be a primitive type in the JSON string but got " + data['voicePreviewText']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['profile_image'] && !(typeof data['profile_image'] === 'string' || data['profile_image'] instanceof String)) {
            throw new Error("Expected the field `profile_image` to be a primitive type in the JSON string but got " + data['profile_image']);
        }
        // ensure the json data is a string
        if (data['short_description'] && !(typeof data['short_description'] === 'string' || data['short_description'] instanceof String)) {
            throw new Error("Expected the field `short_description` to be a primitive type in the JSON string but got " + data['short_description']);
        }
        // ensure the json data is a string
        if (data['introduction'] && !(typeof data['introduction'] === 'string' || data['introduction'] instanceof String)) {
            throw new Error("Expected the field `introduction` to be a primitive type in the JSON string but got " + data['introduction']);
        }
        // ensure the json data is a string
        if (data['owner_uuid'] && !(typeof data['owner_uuid'] === 'string' || data['owner_uuid'] instanceof String)) {
            throw new Error("Expected the field `owner_uuid` to be a primitive type in the JSON string but got " + data['owner_uuid']);
        }
        // ensure the json data is a string
        if (data['system_message'] && !(typeof data['system_message'] === 'string' || data['system_message'] instanceof String)) {
            throw new Error("Expected the field `system_message` to be a primitive type in the JSON string but got " + data['system_message']);
        }
        // validate the optional field `discord_integration`
        if (data['discord_integration']) { // data not null
          V1ReplicasGet200ResponseItemsInnerDiscordIntegration.validateJSON(data['discord_integration']);
        }
        // validate the optional field `telegram_integration`
        if (data['telegram_integration']) { // data not null
          V1ReplicasGet200ResponseItemsInnerTelegramIntegration.validateJSON(data['telegram_integration']);
        }
        // ensure the json data is a string
        if (data['elevenLabsID'] && !(typeof data['elevenLabsID'] === 'string' || data['elevenLabsID'] instanceof String)) {
            throw new Error("Expected the field `elevenLabsID` to be a primitive type in the JSON string but got " + data['elevenLabsID']);
        }

        return true;
    }


}

V1ReplicasGet200ResponseItemsInner.RequiredProperties = ["name", "shortDescription", "greeting", "ownerID", "slug", "llm", "uuid", "profile_image", "short_description", "introduction", "created_at", "owner_uuid", "voice_enabled", "video_enabled", "chat_history_count", "system_message", "discord_integration", "telegram_integration"];

/**
 * The name of the replica.
 * @member {String} name
 */
V1ReplicasGet200ResponseItemsInner.prototype['name'] = undefined;

/**
 * The purpose of the replica. This field is not used for training the replica.
 * @member {String} purpose
 */
V1ReplicasGet200ResponseItemsInner.prototype['purpose'] = undefined;

/**
 * A short description of your replica. This field is not used for training the replica.
 * @member {String} shortDescription
 */
V1ReplicasGet200ResponseItemsInner.prototype['shortDescription'] = undefined;

/**
 * The first thing your replica will say when you start a conversation with them.
 * @member {String} greeting
 */
V1ReplicasGet200ResponseItemsInner.prototype['greeting'] = undefined;

/**
 * The replica type. `individual`: A replica of yourself. `character`: A replica of a character: can be anything you want. `brand`: A replica of a business persona or organization. 
 * @member {module:model/V1ReplicasGet200ResponseItemsInner.TypeEnum} type
 * @default 'character'
 */
V1ReplicasGet200ResponseItemsInner.prototype['type'] = 'character';

/**
 * The replica owner ID.
 * @member {String} ownerID
 */
V1ReplicasGet200ResponseItemsInner.prototype['ownerID'] = undefined;

/**
 * Visibility of the replica. When set to `true`, only the owner will be able to find the replica and chat with it.
 * @member {Boolean} private
 * @default false
 */
V1ReplicasGet200ResponseItemsInner.prototype['private'] = false;

/**
 * Emails of users who can use the replica.
 * @member {Array.<String>} whitelistEmails
 */
V1ReplicasGet200ResponseItemsInner.prototype['whitelistEmails'] = undefined;

/**
 * The slug of the replica. Slugs can be used by API consumers to determine the URLs where replicas can be found.
 * @member {String} slug
 */
V1ReplicasGet200ResponseItemsInner.prototype['slug'] = undefined;

/**
 * The tags associated with the replica. Tags help categorize replicas and make them easier to find.
 * @member {Array.<String>} tags
 */
V1ReplicasGet200ResponseItemsInner.prototype['tags'] = undefined;

/**
 * The URL of the profile image of the replica. The image will be downloaded, optimized and stored on our servers, so the URL in the response will be different. Supported formats: .jpg, .jpeg, .png, .bmp, .webp, .avif
 * @member {String} profileImage
 * @default 'https://sensay.io/assets/default-replica-profile.webp'
 */
V1ReplicasGet200ResponseItemsInner.prototype['profileImage'] = 'https://sensay.io/assets/default-replica-profile.webp';

/**
 * Suggested questions when starting a conversation.
 * @member {Array.<String>} suggestedQuestions
 */
V1ReplicasGet200ResponseItemsInner.prototype['suggestedQuestions'] = undefined;

/**
 * @member {module:model/V1ReplicasGet200ResponseItemsInnerLlm} llm
 */
V1ReplicasGet200ResponseItemsInner.prototype['llm'] = undefined;

/**
 * Text that can be used to generate a voice preview.
 * @member {String} voicePreviewText
 */
V1ReplicasGet200ResponseItemsInner.prototype['voicePreviewText'] = undefined;

/**
 * The replica UUID
 * @member {String} uuid
 */
V1ReplicasGet200ResponseItemsInner.prototype['uuid'] = undefined;

/**
 * The URL of the profile image of the replica. Please use `profileImage` instead.
 * @member {String} profile_image
 */
V1ReplicasGet200ResponseItemsInner.prototype['profile_image'] = undefined;

/**
 * The description of the replica. Please use `shortDescription` instead.
 * @member {String} short_description
 */
V1ReplicasGet200ResponseItemsInner.prototype['short_description'] = undefined;

/**
 * The introduction of the replica. Please use `greeting` instead.
 * @member {String} introduction
 */
V1ReplicasGet200ResponseItemsInner.prototype['introduction'] = undefined;

/**
 * The date and time the replica was created.
 * @member {Date} created_at
 */
V1ReplicasGet200ResponseItemsInner.prototype['created_at'] = undefined;

/**
 * The UUID of the owner of the replica. Please migrate to the new User ID system and use `ownerID` instead.
 * @member {String} owner_uuid
 */
V1ReplicasGet200ResponseItemsInner.prototype['owner_uuid'] = undefined;

/**
 * Whether the replica has voice support.
 * @member {Boolean} voice_enabled
 */
V1ReplicasGet200ResponseItemsInner.prototype['voice_enabled'] = undefined;

/**
 * Whether the replica has video support.
 * @member {Boolean} video_enabled
 */
V1ReplicasGet200ResponseItemsInner.prototype['video_enabled'] = undefined;

/**
 * The total number of chat history items related to this replica, for all users of the organization.
 * @member {Number} chat_history_count
 */
V1ReplicasGet200ResponseItemsInner.prototype['chat_history_count'] = undefined;

/**
 * The replica's tone, personality and behaviour, Please use `llm.systemMessage` instead.
 * @member {String} system_message
 */
V1ReplicasGet200ResponseItemsInner.prototype['system_message'] = undefined;

/**
 * @member {module:model/V1ReplicasGet200ResponseItemsInnerDiscordIntegration} discord_integration
 */
V1ReplicasGet200ResponseItemsInner.prototype['discord_integration'] = undefined;

/**
 * @member {module:model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration} telegram_integration
 */
V1ReplicasGet200ResponseItemsInner.prototype['telegram_integration'] = undefined;

/**
 * The ElevenLabs voice ID associated with this replica.
 * @member {String} elevenLabsID
 */
V1ReplicasGet200ResponseItemsInner.prototype['elevenLabsID'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
V1ReplicasGet200ResponseItemsInner['TypeEnum'] = {

    /**
     * value: "individual"
     * @const
     */
    "individual": "individual",

    /**
     * value: "character"
     * @const
     */
    "character": "character",

    /**
     * value: "brand"
     * @const
     */
    "brand": "brand"
};



export default V1ReplicasGet200ResponseItemsInner;

