/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData from './V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData';

/**
 * The V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest model module.
 * @module model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest</code>.
     * @alias module:model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest
     * @extends Object
     * @param content {String} The prompt to generate completions for, encoded as a string.
     * @param telegramData {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData} 
     */
    constructor(content, telegramData) { 
        
        V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.initialize(this, content, telegramData);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, telegramData) { 
        obj['content'] = content;
        obj['skip_chat_history'] = false;
        obj['telegram_data'] = telegramData;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest} The populated <code>V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('skip_chat_history')) {
                obj['skip_chat_history'] = ApiClient.convertToType(data['skip_chat_history'], 'Boolean');
            }
            if (data.hasOwnProperty('imageURL')) {
                obj['imageURL'] = ApiClient.convertToType(data['imageURL'], 'String');
            }
            if (data.hasOwnProperty('telegram_data')) {
                obj['telegram_data'] = V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData.constructFromObject(data['telegram_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['imageURL'] && !(typeof data['imageURL'] === 'string' || data['imageURL'] instanceof String)) {
            throw new Error("Expected the field `imageURL` to be a primitive type in the JSON string but got " + data['imageURL']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.RequiredProperties = ["content", "telegram_data"];

/**
 * The prompt to generate completions for, encoded as a string.
 * @member {String} content
 */
V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.prototype['content'] = undefined;

/**
 * When set to true, historical messages are not used in the context, and the message is not appended to the conversation history, thus it is excluded from all future chat context.
 * @member {Boolean} skip_chat_history
 * @default false
 */
V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.prototype['skip_chat_history'] = false;

/**
 * The URL of the image to be used as context for the completion.
 * @member {String} imageURL
 */
V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.prototype['imageURL'] = undefined;

/**
 * @member {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData} telegram_data
 */
V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest.prototype['telegram_data'] = undefined;






export default V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest;

