/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest model module.
 * @module model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest</code>.
     * @alias module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest
     * @extends Object
     */
    constructor() { 
        
        V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest} The populated <code>V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('rawText')) {
                obj['rawText'] = ApiClient.convertToType(data['rawText'], 'String');
            }
            if (data.hasOwnProperty('processedText')) {
                obj['processedText'] = ApiClient.convertToType(data['processedText'], 'String');
            }
            if (data.hasOwnProperty('vectorEntryId')) {
                obj['vectorEntryId'] = ApiClient.convertToType(data['vectorEntryId'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['rawText'] && !(typeof data['rawText'] === 'string' || data['rawText'] instanceof String)) {
            throw new Error("Expected the field `rawText` to be a primitive type in the JSON string but got " + data['rawText']);
        }
        // ensure the json data is a string
        if (data['processedText'] && !(typeof data['processedText'] === 'string' || data['processedText'] instanceof String)) {
            throw new Error("Expected the field `processedText` to be a primitive type in the JSON string but got " + data['processedText']);
        }
        // ensure the json data is a string
        if (data['vectorEntryId'] && !(typeof data['vectorEntryId'] === 'string' || data['vectorEntryId'] instanceof String)) {
            throw new Error("Expected the field `vectorEntryId` to be a primitive type in the JSON string but got " + data['vectorEntryId']);
        }

        return true;
    }


}



/**
 * The text content you want your replica to learn
 * @member {String} rawText
 */
V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest.prototype['rawText'] = undefined;

/**
 * Pre-processed text ready for the knowledge base
 * @member {String} processedText
 */
V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest.prototype['processedText'] = undefined;

/**
 * ID of the vector entry in the database
 * @member {String} vectorEntryId
 */
V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest.prototype['vectorEntryId'] = undefined;

/**
 * Additional information about the knowledge base entry (only used with vectorEntryId)
 * @member {Object.<String, Object>} metadata
 */
V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest.prototype['metadata'] = undefined;






export default V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest;

