/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException model module.
 * @module model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException
 * @version 2025-03-25
 */
class V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException {
    /**
     * Constructs a new <code>V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException</code>.
     * The inner exception
     * @alias module:model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException
     * @param name {String} 
     * @param message {String} 
     */
    constructor(name, message) { 
        
        V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.initialize(this, name, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, message) { 
        obj['name'] = name;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException} obj Optional instance to populate.
     * @return {module:model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException} The populated <code>V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('cause')) {
                obj['cause'] = ApiClient.convertToType(data['cause'], 'String');
            }
            if (data.hasOwnProperty('stack')) {
                obj['stack'] = ApiClient.convertToType(data['stack'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['cause'] && !(typeof data['cause'] === 'string' || data['cause'] instanceof String)) {
            throw new Error("Expected the field `cause` to be a primitive type in the JSON string but got " + data['cause']);
        }
        // ensure the json data is a string
        if (data['stack'] && !(typeof data['stack'] === 'string' || data['stack'] instanceof String)) {
            throw new Error("Expected the field `stack` to be a primitive type in the JSON string but got " + data['stack']);
        }

        return true;
    }


}

V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.RequiredProperties = ["name", "message"];

/**
 * @member {String} name
 */
V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.prototype['name'] = undefined;

/**
 * @member {String} message
 */
V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.prototype['message'] = undefined;

/**
 * @member {String} cause
 */
V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.prototype['cause'] = undefined;

/**
 * @member {String} stack
 */
V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException.prototype['stack'] = undefined;






export default V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException;

