/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1TrainingGet200ResponseItemsInner from './V1TrainingGet200ResponseItemsInner';

/**
 * The V1TrainingGet200Response model module.
 * @module model/V1TrainingGet200Response
 * @version 2025-03-25
 */
class V1TrainingGet200Response {
    /**
     * Constructs a new <code>V1TrainingGet200Response</code>.
     * @alias module:model/V1TrainingGet200Response
     * @param success {Boolean} Indicates if the list operation was successful
     * @param items {Array.<module:model/V1TrainingGet200ResponseItemsInner>} Array of knowledge base entries matching your query parameters
     */
    constructor(success, items) { 
        
        V1TrainingGet200Response.initialize(this, success, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, items) { 
        obj['success'] = success;
        obj['items'] = items;
    }

    /**
     * Constructs a <code>V1TrainingGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1TrainingGet200Response} obj Optional instance to populate.
     * @return {module:model/V1TrainingGet200Response} The populated <code>V1TrainingGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1TrainingGet200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [V1TrainingGet200ResponseItemsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1TrainingGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1TrainingGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1TrainingGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                V1TrainingGet200ResponseItemsInner.validateJSON(item);
            };
        }

        return true;
    }


}

V1TrainingGet200Response.RequiredProperties = ["success", "items"];

/**
 * Indicates if the list operation was successful
 * @member {Boolean} success
 */
V1TrainingGet200Response.prototype['success'] = undefined;

/**
 * Array of knowledge base entries matching your query parameters
 * @member {Array.<module:model/V1TrainingGet200ResponseItemsInner>} items
 */
V1TrainingGet200Response.prototype['items'] = undefined;






export default V1TrainingGet200Response;

