/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1TrainingTrainingIDDelete200Response model module.
 * @module model/V1TrainingTrainingIDDelete200Response
 * @version 2025-03-25
 */
class V1TrainingTrainingIDDelete200Response {
    /**
     * Constructs a new <code>V1TrainingTrainingIDDelete200Response</code>.
     * @alias module:model/V1TrainingTrainingIDDelete200Response
     * @param success {Boolean} Indicates whether the knowledge base entry and its associated vector embeddings were successfully deleted from the system
     */
    constructor(success) { 
        
        V1TrainingTrainingIDDelete200Response.initialize(this, success);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success) { 
        obj['success'] = success;
    }

    /**
     * Constructs a <code>V1TrainingTrainingIDDelete200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1TrainingTrainingIDDelete200Response} obj Optional instance to populate.
     * @return {module:model/V1TrainingTrainingIDDelete200Response} The populated <code>V1TrainingTrainingIDDelete200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1TrainingTrainingIDDelete200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1TrainingTrainingIDDelete200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1TrainingTrainingIDDelete200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1TrainingTrainingIDDelete200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

V1TrainingTrainingIDDelete200Response.RequiredProperties = ["success"];

/**
 * Indicates whether the knowledge base entry and its associated vector embeddings were successfully deleted from the system
 * @member {Boolean} success
 */
V1TrainingTrainingIDDelete200Response.prototype['success'] = undefined;






export default V1TrainingTrainingIDDelete200Response;

