/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TheLinkedAccountsOfTheUserInner from './TheLinkedAccountsOfTheUserInner';

/**
 * The V1UsersMeGet200Response model module.
 * @module model/V1UsersMeGet200Response
 * @version 2025-03-25
 */
class V1UsersMeGet200Response {
    /**
     * Constructs a new <code>V1UsersMeGet200Response</code>.
     * @alias module:model/V1UsersMeGet200Response
     * @extends Object
     * @param id {String} The ID of the user
     */
    constructor(id) { 
        
        V1UsersMeGet200Response.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>V1UsersMeGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1UsersMeGet200Response} obj Optional instance to populate.
     * @return {module:model/V1UsersMeGet200Response} The populated <code>V1UsersMeGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1UsersMeGet200Response();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('linkedAccounts')) {
                obj['linkedAccounts'] = ApiClient.convertToType(data['linkedAccounts'], [TheLinkedAccountsOfTheUserInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1UsersMeGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1UsersMeGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1UsersMeGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['linkedAccounts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['linkedAccounts'])) {
                throw new Error("Expected the field `linkedAccounts` to be an array in the JSON data but got " + data['linkedAccounts']);
            }
            // validate the optional field `linkedAccounts` (array)
            for (const item of data['linkedAccounts']) {
                TheLinkedAccountsOfTheUserInner.validateJSON(item);
            };
        }

        return true;
    }


}

V1UsersMeGet200Response.RequiredProperties = ["id"];

/**
 * The name of the user
 * @member {String} name
 */
V1UsersMeGet200Response.prototype['name'] = undefined;

/**
 * The email address
 * @member {String} email
 */
V1UsersMeGet200Response.prototype['email'] = undefined;

/**
 * The ID of the user
 * @member {String} id
 */
V1UsersMeGet200Response.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/TheLinkedAccountsOfTheUserInner>} linkedAccounts
 */
V1UsersMeGet200Response.prototype['linkedAccounts'] = undefined;






export default V1UsersMeGet200Response;

