/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebhookRequestRecordMetadata model module.
 * @module model/WebhookRequestRecordMetadata
 * @version 2025-03-25
 */
class WebhookRequestRecordMetadata {
    /**
     * Constructs a new <code>WebhookRequestRecordMetadata</code>.
     * @alias module:model/WebhookRequestRecordMetadata
     * @param size {Number} 
     * @param mimetype {String} 
     */
    constructor(size, mimetype) { 
        
        WebhookRequestRecordMetadata.initialize(this, size, mimetype);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, size, mimetype) { 
        obj['size'] = size;
        obj['mimetype'] = mimetype;
    }

    /**
     * Constructs a <code>WebhookRequestRecordMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookRequestRecordMetadata} obj Optional instance to populate.
     * @return {module:model/WebhookRequestRecordMetadata} The populated <code>WebhookRequestRecordMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookRequestRecordMetadata();

            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('mimetype')) {
                obj['mimetype'] = ApiClient.convertToType(data['mimetype'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookRequestRecordMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookRequestRecordMetadata</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookRequestRecordMetadata.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['mimetype'] && !(typeof data['mimetype'] === 'string' || data['mimetype'] instanceof String)) {
            throw new Error("Expected the field `mimetype` to be a primitive type in the JSON string but got " + data['mimetype']);
        }

        return true;
    }


}

WebhookRequestRecordMetadata.RequiredProperties = ["size", "mimetype"];

/**
 * @member {Number} size
 */
WebhookRequestRecordMetadata.prototype['size'] = undefined;

/**
 * @member {String} mimetype
 */
WebhookRequestRecordMetadata.prototype['mimetype'] = undefined;






export default WebhookRequestRecordMetadata;

