/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebhookRequestRecordMetadata from './WebhookRequestRecordMetadata';

/**
 * The WebhookRequestRecord model module.
 * @module model/WebhookRequestRecord
 * @version 2025-03-25
 */
class WebhookRequestRecord {
    /**
     * Constructs a new <code>WebhookRequestRecord</code>.
     * @alias module:model/WebhookRequestRecord
     * @param id {String} 
     * @param bucketId {String} 
     * @param pathTokens {Array.<String>} 
     * @param metadata {module:model/WebhookRequestRecordMetadata} 
     */
    constructor(id, bucketId, pathTokens, metadata) { 
        
        WebhookRequestRecord.initialize(this, id, bucketId, pathTokens, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, bucketId, pathTokens, metadata) { 
        obj['id'] = id;
        obj['bucket_id'] = bucketId;
        obj['path_tokens'] = pathTokens;
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>WebhookRequestRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookRequestRecord} obj Optional instance to populate.
     * @return {module:model/WebhookRequestRecord} The populated <code>WebhookRequestRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookRequestRecord();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('bucket_id')) {
                obj['bucket_id'] = ApiClient.convertToType(data['bucket_id'], 'String');
            }
            if (data.hasOwnProperty('path_tokens')) {
                obj['path_tokens'] = ApiClient.convertToType(data['path_tokens'], ['String']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = WebhookRequestRecordMetadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookRequestRecord</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookRequestRecord</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookRequestRecord.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['bucket_id'] && !(typeof data['bucket_id'] === 'string' || data['bucket_id'] instanceof String)) {
            throw new Error("Expected the field `bucket_id` to be a primitive type in the JSON string but got " + data['bucket_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['path_tokens'])) {
            throw new Error("Expected the field `path_tokens` to be an array in the JSON data but got " + data['path_tokens']);
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          WebhookRequestRecordMetadata.validateJSON(data['metadata']);
        }

        return true;
    }


}

WebhookRequestRecord.RequiredProperties = ["id", "bucket_id", "path_tokens", "metadata"];

/**
 * @member {String} id
 */
WebhookRequestRecord.prototype['id'] = undefined;

/**
 * @member {String} bucket_id
 */
WebhookRequestRecord.prototype['bucket_id'] = undefined;

/**
 * @member {Array.<String>} path_tokens
 */
WebhookRequestRecord.prototype['path_tokens'] = undefined;

/**
 * @member {module:model/WebhookRequestRecordMetadata} metadata
 */
WebhookRequestRecord.prototype['metadata'] = undefined;






export default WebhookRequestRecord;

