/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import TheLinkedAccountsOfTheUserInner from './model/TheLinkedAccountsOfTheUserInner';
import V1ApiKeysInvitesCodeRedeemPost200Response from './model/V1ApiKeysInvitesCodeRedeemPost200Response';
import V1ApiKeysInvitesCodeRedeemPostRequest from './model/V1ApiKeysInvitesCodeRedeemPostRequest';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response from './model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner from './model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage from './model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage from './model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest from './model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner from './model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner';
import V1ReplicasGet200Response from './model/V1ReplicasGet200Response';
import V1ReplicasGet200ResponseItemsInner from './model/V1ReplicasGet200ResponseItemsInner';
import V1ReplicasGet200ResponseItemsInnerDiscordIntegration from './model/V1ReplicasGet200ResponseItemsInnerDiscordIntegration';
import V1ReplicasGet200ResponseItemsInnerLlm from './model/V1ReplicasGet200ResponseItemsInnerLlm';
import V1ReplicasGet200ResponseItemsInnerTelegramIntegration from './model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration';
import V1ReplicasPost201Response from './model/V1ReplicasPost201Response';
import V1ReplicasPostRequest from './model/V1ReplicasPostRequest';
import V1ReplicasReplicaUUIDChatCompletionsPost200Response from './model/V1ReplicasReplicaUUIDChatCompletionsPost200Response';
import V1ReplicasReplicaUUIDChatCompletionsPostRequest from './model/V1ReplicasReplicaUUIDChatCompletionsPostRequest';
import V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest from './model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest';
import V1ReplicasReplicaUUIDChatHistoryGet200Response from './model/V1ReplicasReplicaUUIDChatHistoryGet200Response';
import V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner from './model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner';
import V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner from './model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner';
import V1ReplicasReplicaUUIDChatHistoryPostRequest from './model/V1ReplicasReplicaUUIDChatHistoryPostRequest';
import V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData from './model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData';
import V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest from './model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest';
import V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData from './model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData';
import V1ReplicasReplicaUUIDDelete200Response from './model/V1ReplicasReplicaUUIDDelete200Response';
import V1ReplicasReplicaUUIDGet200Response from './model/V1ReplicasReplicaUUIDGet200Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response from './model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response from './model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response from './model/V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest from './model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest';
import V1ReplicasReplicaUUIDPut200Response from './model/V1ReplicasReplicaUUIDPut200Response';
import V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response from './model/V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response';
import V1ReplicasReplicaUUIDTrainingPost200Response from './model/V1ReplicasReplicaUUIDTrainingPost200Response';
import V1ReplicasReplicaUUIDTrainingPost400Response from './model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from './model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from './model/V1ReplicasReplicaUUIDTrainingPost500Response';
import V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException from './model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException';
import V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response from './model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response';
import V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest from './model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest';
import V1TrainingGet200Response from './model/V1TrainingGet200Response';
import V1TrainingGet200ResponseItemsInner from './model/V1TrainingGet200ResponseItemsInner';
import V1TrainingTrainingIDDelete200Response from './model/V1TrainingTrainingIDDelete200Response';
import V1UsersMeGet200Response from './model/V1UsersMeGet200Response';
import V1UsersPostRequest from './model/V1UsersPostRequest';
import WebhookRequest from './model/WebhookRequest';
import WebhookRequestRecord from './model/WebhookRequestRecord';
import WebhookRequestRecordMetadata from './model/WebhookRequestRecordMetadata';
import APIKeysApi from './api/APIKeysApi';
import ChatCompletionsApi from './api/ChatCompletionsApi';
import ChatHistoryApi from './api/ChatHistoryApi';
import ChatWidgetIntegrationApi from './api/ChatWidgetIntegrationApi';
import DiscordIntegrationApi from './api/DiscordIntegrationApi';
import ExperimentalApi from './api/ExperimentalApi';
import ReplicasApi from './api/ReplicasApi';
import TelegramIntegrationApi from './api/TelegramIntegrationApi';
import TrainingApi from './api/TrainingApi';
import UsersApi from './api/UsersApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SensayApi = require('index'); // See note below*.
* var xxxSvc = new SensayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SensayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SensayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SensayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2025-03-25
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The TheLinkedAccountsOfTheUserInner model constructor.
     * @property {module:model/TheLinkedAccountsOfTheUserInner}
     */
    TheLinkedAccountsOfTheUserInner,

    /**
     * The V1ApiKeysInvitesCodeRedeemPost200Response model constructor.
     * @property {module:model/V1ApiKeysInvitesCodeRedeemPost200Response}
     */
    V1ApiKeysInvitesCodeRedeemPost200Response,

    /**
     * The V1ApiKeysInvitesCodeRedeemPostRequest model constructor.
     * @property {module:model/V1ApiKeysInvitesCodeRedeemPostRequest}
     */
    V1ApiKeysInvitesCodeRedeemPostRequest,

    /**
     * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response model constructor.
     * @property {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response}
     */
    V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response,

    /**
     * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner model constructor.
     * @property {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner}
     */
    V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInner,

    /**
     * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage model constructor.
     * @property {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage}
     */
    V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseChoicesInnerMessage,

    /**
     * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage model constructor.
     * @property {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage}
     */
    V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200ResponseUsage,

    /**
     * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest model constructor.
     * @property {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest}
     */
    V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest,

    /**
     * The V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner model constructor.
     * @property {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner}
     */
    V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequestMessagesInner,

    /**
     * The V1ReplicasGet200Response model constructor.
     * @property {module:model/V1ReplicasGet200Response}
     */
    V1ReplicasGet200Response,

    /**
     * The V1ReplicasGet200ResponseItemsInner model constructor.
     * @property {module:model/V1ReplicasGet200ResponseItemsInner}
     */
    V1ReplicasGet200ResponseItemsInner,

    /**
     * The V1ReplicasGet200ResponseItemsInnerDiscordIntegration model constructor.
     * @property {module:model/V1ReplicasGet200ResponseItemsInnerDiscordIntegration}
     */
    V1ReplicasGet200ResponseItemsInnerDiscordIntegration,

    /**
     * The V1ReplicasGet200ResponseItemsInnerLlm model constructor.
     * @property {module:model/V1ReplicasGet200ResponseItemsInnerLlm}
     */
    V1ReplicasGet200ResponseItemsInnerLlm,

    /**
     * The V1ReplicasGet200ResponseItemsInnerTelegramIntegration model constructor.
     * @property {module:model/V1ReplicasGet200ResponseItemsInnerTelegramIntegration}
     */
    V1ReplicasGet200ResponseItemsInnerTelegramIntegration,

    /**
     * The V1ReplicasPost201Response model constructor.
     * @property {module:model/V1ReplicasPost201Response}
     */
    V1ReplicasPost201Response,

    /**
     * The V1ReplicasPostRequest model constructor.
     * @property {module:model/V1ReplicasPostRequest}
     */
    V1ReplicasPostRequest,

    /**
     * The V1ReplicasReplicaUUIDChatCompletionsPost200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatCompletionsPost200Response}
     */
    V1ReplicasReplicaUUIDChatCompletionsPost200Response,

    /**
     * The V1ReplicasReplicaUUIDChatCompletionsPostRequest model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatCompletionsPostRequest}
     */
    V1ReplicasReplicaUUIDChatCompletionsPostRequest,

    /**
     * The V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest}
     */
    V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryGet200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response}
     */
    V1ReplicasReplicaUUIDChatHistoryGet200Response,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner}
     */
    V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInner,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner}
     */
    V1ReplicasReplicaUUIDChatHistoryGet200ResponseItemsInnerSourcesInner,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryPostRequest model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequest}
     */
    V1ReplicasReplicaUUIDChatHistoryPostRequest,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData}
     */
    V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest}
     */
    V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest,

    /**
     * The V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData}
     */
    V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData,

    /**
     * The V1ReplicasReplicaUUIDDelete200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDDelete200Response}
     */
    V1ReplicasReplicaUUIDDelete200Response,

    /**
     * The V1ReplicasReplicaUUIDGet200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDGet200Response}
     */
    V1ReplicasReplicaUUIDGet200Response,

    /**
     * The V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response}
     */
    V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response,

    /**
     * The V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response}
     */
    V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response,

    /**
     * The V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response}
     */
    V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response,

    /**
     * The V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest}
     */
    V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest,

    /**
     * The V1ReplicasReplicaUUIDPut200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDPut200Response}
     */
    V1ReplicasReplicaUUIDPut200Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response}
     */
    V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingPost200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingPost200Response}
     */
    V1ReplicasReplicaUUIDTrainingPost200Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingPost400Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingPost400Response}
     */
    V1ReplicasReplicaUUIDTrainingPost400Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingPost404Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingPost404Response}
     */
    V1ReplicasReplicaUUIDTrainingPost404Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingPost500Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingPost500Response}
     */
    V1ReplicasReplicaUUIDTrainingPost500Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException}
     */
    V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException,

    /**
     * The V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response}
     */
    V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response,

    /**
     * The V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest model constructor.
     * @property {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest}
     */
    V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest,

    /**
     * The V1TrainingGet200Response model constructor.
     * @property {module:model/V1TrainingGet200Response}
     */
    V1TrainingGet200Response,

    /**
     * The V1TrainingGet200ResponseItemsInner model constructor.
     * @property {module:model/V1TrainingGet200ResponseItemsInner}
     */
    V1TrainingGet200ResponseItemsInner,

    /**
     * The V1TrainingTrainingIDDelete200Response model constructor.
     * @property {module:model/V1TrainingTrainingIDDelete200Response}
     */
    V1TrainingTrainingIDDelete200Response,

    /**
     * The V1UsersMeGet200Response model constructor.
     * @property {module:model/V1UsersMeGet200Response}
     */
    V1UsersMeGet200Response,

    /**
     * The V1UsersPostRequest model constructor.
     * @property {module:model/V1UsersPostRequest}
     */
    V1UsersPostRequest,

    /**
     * The WebhookRequest model constructor.
     * @property {module:model/WebhookRequest}
     */
    WebhookRequest,

    /**
     * The WebhookRequestRecord model constructor.
     * @property {module:model/WebhookRequestRecord}
     */
    WebhookRequestRecord,

    /**
     * The WebhookRequestRecordMetadata model constructor.
     * @property {module:model/WebhookRequestRecordMetadata}
     */
    WebhookRequestRecordMetadata,

    /**
    * The APIKeysApi service constructor.
    * @property {module:api/APIKeysApi}
    */
    APIKeysApi,

    /**
    * The ChatCompletionsApi service constructor.
    * @property {module:api/ChatCompletionsApi}
    */
    ChatCompletionsApi,

    /**
    * The ChatHistoryApi service constructor.
    * @property {module:api/ChatHistoryApi}
    */
    ChatHistoryApi,

    /**
    * The ChatWidgetIntegrationApi service constructor.
    * @property {module:api/ChatWidgetIntegrationApi}
    */
    ChatWidgetIntegrationApi,

    /**
    * The DiscordIntegrationApi service constructor.
    * @property {module:api/DiscordIntegrationApi}
    */
    DiscordIntegrationApi,

    /**
    * The ExperimentalApi service constructor.
    * @property {module:api/ExperimentalApi}
    */
    ExperimentalApi,

    /**
    * The ReplicasApi service constructor.
    * @property {module:api/ReplicasApi}
    */
    ReplicasApi,

    /**
    * The TelegramIntegrationApi service constructor.
    * @property {module:api/TelegramIntegrationApi}
    */
    TelegramIntegrationApi,

    /**
    * The TrainingApi service constructor.
    * @property {module:api/TrainingApi}
    */
    TrainingApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
