/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ApiKeysInvitesCodeRedeemPost200Response from '../model/V1ApiKeysInvitesCodeRedeemPost200Response';
import V1ApiKeysInvitesCodeRedeemPostRequest from '../model/V1ApiKeysInvitesCodeRedeemPostRequest';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';

/**
* APIKeys service.
* @module api/APIKeysApi
* @version 2025-03-25
*/
export default class APIKeysApi {

    /**
    * Constructs a new APIKeysApi. 
    * @alias module:api/APIKeysApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ApiKeysInvitesCodeRedeemPost operation.
     * @callback module:api/APIKeysApi~v1ApiKeysInvitesCodeRedeemPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ApiKeysInvitesCodeRedeemPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Redeem an API key invitation
     *    If you have an invitation code, you can redeem it to create an Organization and an API key associated with it.   
     * @param {String} code 
     * @param {Object} opts Optional parameters
     * @param {module:model/V1ApiKeysInvitesCodeRedeemPostRequest} [v1ApiKeysInvitesCodeRedeemPostRequest] 
     * @param {module:api/APIKeysApi~v1ApiKeysInvitesCodeRedeemPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ApiKeysInvitesCodeRedeemPost200Response}
     */
    v1ApiKeysInvitesCodeRedeemPost(code, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ApiKeysInvitesCodeRedeemPostRequest'];
      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling v1ApiKeysInvitesCodeRedeemPost");
      }

      let pathParams = {
        'code': code
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ApiKeysInvitesCodeRedeemPost200Response;
      return this.apiClient.callApi(
        '/v1/api-keys/invites/{code}/redeem', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
