/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response from '../model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest from '../model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest';
import V1ReplicasReplicaUUIDChatCompletionsPost200Response from '../model/V1ReplicasReplicaUUIDChatCompletionsPost200Response';
import V1ReplicasReplicaUUIDChatCompletionsPostRequest from '../model/V1ReplicasReplicaUUIDChatCompletionsPostRequest';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';

/**
* ChatCompletions service.
* @module api/ChatCompletionsApi
* @version 2025-03-25
*/
export default class ChatCompletionsApi {

    /**
    * Constructs a new ChatCompletionsApi. 
    * @alias module:api/ChatCompletionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ExperimentalReplicasReplicaUUIDChatCompletionsPost operation.
     * @callback module:api/ChatCompletionsApi~v1ExperimentalReplicasReplicaUUIDChatCompletionsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate a completion (OpenAI-compatible, non-streaming)
     *    > warn   > Limited [OpenAI Chat Completions API](https://platform.openai.com/docs/api-reference/chat/create) compatibility.   > Supports basic chat completion with standard message roles and JSON responses.   > Not supported: OpenAI-style streaming, tool calls, stop sequences, logprobs, and most request parameters.    Creates a chat completion response from a list of messages comprising a conversation.   
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest} [v1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest] 
     * @param {module:api/ChatCompletionsApi~v1ExperimentalReplicasReplicaUUIDChatCompletionsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response}
     */
    v1ExperimentalReplicasReplicaUUIDChatCompletionsPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ExperimentalReplicasReplicaUUIDChatCompletionsPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response;
      return this.apiClient.callApi(
        '/v1/experimental/replicas/{replicaUUID}/chat/completions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatCompletionsPost operation.
     * @callback module:api/ChatCompletionsApi~v1ReplicasReplicaUUIDChatCompletionsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDChatCompletionsPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate a completion
     *    Ask for a completion and stores the prompt in the chat history.    Replica chat supports two response formats: streamed and JSON. To switch between these formats, use the 'Accept' header, specifying either 'text/event-stream' for streaming or 'application/json' for JSON.   The streamed response honours the [Stream Protocol](https://sdk.vercel.ai/docs/ai-sdk-ui/stream-protocol), allowing the use of a number of SDKs, including [Vercel AI SDK](https://sdk.vercel.ai/docs/introduction).    The streamed variant is not specified in the OpenAPI Schema because it is not an OpenAPI endpoint.   
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1ReplicasReplicaUUIDChatCompletionsPostRequest} [v1ReplicasReplicaUUIDChatCompletionsPostRequest] 
     * @param {module:api/ChatCompletionsApi~v1ReplicasReplicaUUIDChatCompletionsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDChatCompletionsPost200Response}
     */
    v1ReplicasReplicaUUIDChatCompletionsPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasReplicaUUIDChatCompletionsPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatCompletionsPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'text/event-stream'];
      let returnType = V1ReplicasReplicaUUIDChatCompletionsPost200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/completions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
