/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ReplicasReplicaUUIDChatHistoryGet200Response from '../model/V1ReplicasReplicaUUIDChatHistoryGet200Response';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';

/**
* ChatWidgetIntegration service.
* @module api/ChatWidgetIntegrationApi
* @version 2025-03-25
*/
export default class ChatWidgetIntegrationApi {

    /**
    * Constructs a new ChatWidgetIntegrationApi. 
    * @alias module:api/ChatWidgetIntegrationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatHistoryEmbedGet operation.
     * @callback module:api/ChatWidgetIntegrationApi~v1ReplicasReplicaUUIDChatHistoryEmbedGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Embed chat history
     * List embed chat history items of a Replica belonging to the logged in user.
     * @param {String} replicaUUID 
     * @param {module:api/ChatWidgetIntegrationApi~v1ReplicasReplicaUUIDChatHistoryEmbedGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response}
     */
    v1ReplicasReplicaUUIDChatHistoryEmbedGet(replicaUUID, callback) {
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatHistoryEmbedGet");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDChatHistoryGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/history/embed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
