/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ReplicasReplicaUUIDChatHistoryGet200Response from '../model/V1ReplicasReplicaUUIDChatHistoryGet200Response';
import V1ReplicasReplicaUUIDChatHistoryPostRequest from '../model/V1ReplicasReplicaUUIDChatHistoryPostRequest';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';
import V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response from '../model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response';

/**
* ChatHistory service.
* @module api/ChatHistoryApi
* @version 2025-03-25
*/
export default class ChatHistoryApi {

    /**
    * Constructs a new ChatHistoryApi. 
    * @alias module:api/ChatHistoryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatHistoryGet operation.
     * @callback module:api/ChatHistoryApi~v1ReplicasReplicaUUIDChatHistoryGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get chat history
     * List chat history items of a Replica belonging to the logged in user.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/ChatHistoryApi~v1ReplicasReplicaUUIDChatHistoryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response}
     */
    v1ReplicasReplicaUUIDChatHistoryGet(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatHistoryGet");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDChatHistoryGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/history', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatHistoryPost operation.
     * @callback module:api/ChatHistoryApi~v1ReplicasReplicaUUIDChatHistoryPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a chat history entry
     * Save chat history items of a Replica belonging to the logged in user.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryPostRequest} [v1ReplicasReplicaUUIDChatHistoryPostRequest] 
     * @param {module:api/ChatHistoryApi~v1ReplicasReplicaUUIDChatHistoryPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response}
     */
    v1ReplicasReplicaUUIDChatHistoryPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasReplicaUUIDChatHistoryPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatHistoryPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/history', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatHistoryWebGet operation.
     * @callback module:api/ChatHistoryApi~v1ReplicasReplicaUUIDChatHistoryWebGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Web chat history
     * List web chat history items of a Replica belonging to the logged in user.
     * @param {String} replicaUUID 
     * @param {module:api/ChatHistoryApi~v1ReplicasReplicaUUIDChatHistoryWebGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response}
     */
    v1ReplicasReplicaUUIDChatHistoryWebGet(replicaUUID, callback) {
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatHistoryWebGet");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDChatHistoryGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/history/web', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
