/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response from '../model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response';
import V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest from '../model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';

/**
* Experimental service.
* @module api/ExperimentalApi
* @version 2025-03-25
*/
export default class ExperimentalApi {

    /**
    * Constructs a new ExperimentalApi. 
    * @alias module:api/ExperimentalApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ExperimentalReplicasReplicaUUIDChatCompletionsPost operation.
     * @callback module:api/ExperimentalApi~v1ExperimentalReplicasReplicaUUIDChatCompletionsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate a completion (OpenAI-compatible, non-streaming)
     *    > warn   > Limited [OpenAI Chat Completions API](https://platform.openai.com/docs/api-reference/chat/create) compatibility.   > Supports basic chat completion with standard message roles and JSON responses.   > Not supported: OpenAI-style streaming, tool calls, stop sequences, logprobs, and most request parameters.    Creates a chat completion response from a list of messages comprising a conversation.   
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest} [v1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest] 
     * @param {module:api/ExperimentalApi~v1ExperimentalReplicasReplicaUUIDChatCompletionsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response}
     */
    v1ExperimentalReplicasReplicaUUIDChatCompletionsPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ExperimentalReplicasReplicaUUIDChatCompletionsPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ExperimentalReplicasReplicaUUIDChatCompletionsPost200Response;
      return this.apiClient.callApi(
        '/v1/experimental/replicas/{replicaUUID}/chat/completions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
