/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ReplicasGet200Response from '../model/V1ReplicasGet200Response';
import V1ReplicasPost201Response from '../model/V1ReplicasPost201Response';
import V1ReplicasPostRequest from '../model/V1ReplicasPostRequest';
import V1ReplicasReplicaUUIDDelete200Response from '../model/V1ReplicasReplicaUUIDDelete200Response';
import V1ReplicasReplicaUUIDGet200Response from '../model/V1ReplicasReplicaUUIDGet200Response';
import V1ReplicasReplicaUUIDPut200Response from '../model/V1ReplicasReplicaUUIDPut200Response';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';

/**
* Replicas service.
* @module api/ReplicasApi
* @version 2025-03-25
*/
export default class ReplicasApi {

    /**
    * Constructs a new ReplicasApi. 
    * @alias module:api/ReplicasApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ReplicasGet operation.
     * @callback module:api/ReplicasApi~v1ReplicasGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List replicas
     * List replicas with pagination with optional filtering. Only Replicas that are public or belong to the authenticated user are returned.
     * @param {Object} opts Optional parameters
     * @param {String} [ownerUuid] Filters by the owner UUID of the Replicas
     * @param {String} [ownerID] The replica owner ID.
     * @param {Number} [pageIndex = 1)] Pagination: The page index to return
     * @param {Number} [pageSize = 24)] Pagination: The number of items per page
     * @param {String} [slug] Filters by the replica's slug
     * @param {String} [search] Search: by name of Replica, sorted in ascending order
     * @param {Array.<module:model/String>} [tags] Filters by tags associated to Replicas
     * @param {module:model/String} [sort = 'name')] Sorts by name or popularity of Replicas in ascending order
     * @param {module:model/String} [integration] Filters by integration
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/ReplicasApi~v1ReplicasGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasGet200Response}
     */
    v1ReplicasGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'owner_uuid': opts['ownerUuid'],
        'ownerID': opts['ownerID'],
        'page_index': opts['pageIndex'],
        'page_size': opts['pageSize'],
        'slug': opts['slug'],
        'search': opts['search'],
        'tags': this.apiClient.buildCollectionParam(opts['tags'], 'multi'),
        'sort': opts['sort'],
        'integration': opts['integration']
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasPost operation.
     * @callback module:api/ReplicasApi~v1ReplicasPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a replica
     * Creates a new replica.
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1ReplicasPostRequest} [v1ReplicasPostRequest] 
     * @param {module:api/ReplicasApi~v1ReplicasPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasPost201Response}
     */
    v1ReplicasPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasPostRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ReplicasPost201Response;
      return this.apiClient.callApi(
        '/v1/replicas', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDDelete operation.
     * @callback module:api/ReplicasApi~v1ReplicasReplicaUUIDDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDDelete200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a replica
     * Deletes a replica by UUID.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/ReplicasApi~v1ReplicasReplicaUUIDDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDDelete200Response}
     */
    v1ReplicasReplicaUUIDDelete(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDDelete");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDDelete200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDGet operation.
     * @callback module:api/ReplicasApi~v1ReplicasReplicaUUIDGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a replica
     * Get an existing replica.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/ReplicasApi~v1ReplicasReplicaUUIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDGet200Response}
     */
    v1ReplicasReplicaUUIDGet(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDGet");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDPut operation.
     * @callback module:api/ReplicasApi~v1ReplicasReplicaUUIDPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDPut200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a replica
     * Updates an existing replica.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1ReplicasPostRequest} [v1ReplicasPostRequest] 
     * @param {module:api/ReplicasApi~v1ReplicasReplicaUUIDPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDPut200Response}
     */
    v1ReplicasReplicaUUIDPut(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDPut");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDPut200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
