/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ReplicasReplicaUUIDChatCompletionsPost200Response from '../model/V1ReplicasReplicaUUIDChatCompletionsPost200Response';
import V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest from '../model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest';
import V1ReplicasReplicaUUIDChatHistoryGet200Response from '../model/V1ReplicasReplicaUUIDChatHistoryGet200Response';
import V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest from '../model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest';
import V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response from '../model/V1ReplicasReplicaUUIDIntegrationsTelegramDelete202Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response from '../model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response from '../model/V1ReplicasReplicaUUIDIntegrationsTelegramPost202Response';
import V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest from '../model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';
import V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response from '../model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response';

/**
* TelegramIntegration service.
* @module api/TelegramIntegrationApi
* @version 2025-03-25
*/
export default class TelegramIntegrationApi {

    /**
    * Constructs a new TelegramIntegrationApi. 
    * @alias module:api/TelegramIntegrationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatCompletionsTelegramPost operation.
     * @callback module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDChatCompletionsTelegramPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDChatCompletionsPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate a Telegram completion
     *      Ask for a completion and stores the prompt in the chat history.        Replica chat supports two response formats: streamed and JSON. To switch between these formats, use the 'Accept' header, specifying either 'text/event-stream' for streaming or 'application/json' for JSON.     The streamed response honours the [Stream Protocol](https://sdk.vercel.ai/docs/ai-sdk-ui/stream-protocol), allowing the use of a number of SDKs, including [Vercel AI SDK](https://sdk.vercel.ai/docs/introduction).        The streamed variant is not specified in the OpenAPI Schema because it is not an OpenAPI endpoint.     
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {module:model/V1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest} [v1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest] 
     * @param {module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDChatCompletionsTelegramPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDChatCompletionsPost200Response}
     */
    v1ReplicasReplicaUUIDChatCompletionsTelegramPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasReplicaUUIDChatCompletionsTelegramPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatCompletionsTelegramPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'text/event-stream'];
      let returnType = V1ReplicasReplicaUUIDChatCompletionsPost200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/completions/telegram', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatHistoryTelegramGet operation.
     * @callback module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDChatHistoryTelegramGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Telegram chat history
     * List telegram chat history items of a Replica belonging to the logged in user.
     * @param {String} replicaUUID 
     * @param {module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDChatHistoryTelegramGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDChatHistoryGet200Response}
     */
    v1ReplicasReplicaUUIDChatHistoryTelegramGet(replicaUUID, callback) {
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatHistoryTelegramGet");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDChatHistoryGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/history/telegram', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDChatHistoryTelegramPost operation.
     * @callback module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDChatHistoryTelegramPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Telegram chat history entry
     * Save chat history items of a Replica belonging to the logged in user.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {module:model/V1ReplicasReplicaUUIDChatHistoryTelegramPostRequest} [v1ReplicasReplicaUUIDChatHistoryTelegramPostRequest] 
     * @param {module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDChatHistoryTelegramPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response}
     */
    v1ReplicasReplicaUUIDChatHistoryTelegramPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasReplicaUUIDChatHistoryTelegramPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDChatHistoryTelegramPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/chat/history/telegram', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDIntegrationsTelegramDelete operation.
     * @callback module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDIntegrationsTelegramDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a replica Telegram integration
     * Removes a replica Telegram integration.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDIntegrationsTelegramDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response}
     */
    v1ReplicasReplicaUUIDIntegrationsTelegramDelete(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDIntegrationsTelegramDelete");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/integrations/telegram', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDIntegrationsTelegramPost operation.
     * @callback module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDIntegrationsTelegramPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a replica Telegram integration
     * Integrates a replica to Telegram. The default Sensay Telegram integration will run a bot for you until you delete the integration.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPostRequest} [v1ReplicasReplicaUUIDIntegrationsTelegramPostRequest] 
     * @param {module:api/TelegramIntegrationApi~v1ReplicasReplicaUUIDIntegrationsTelegramPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response}
     */
    v1ReplicasReplicaUUIDIntegrationsTelegramPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasReplicaUUIDIntegrationsTelegramPostRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDIntegrationsTelegramPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDIntegrationsTelegramPost200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/integrations/telegram', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
