/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response from '../model/V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response';
import V1ReplicasReplicaUUIDTrainingPost200Response from '../model/V1ReplicasReplicaUUIDTrainingPost200Response';
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';
import V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response from '../model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response';
import V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest from '../model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest';
import V1TrainingGet200Response from '../model/V1TrainingGet200Response';
import V1TrainingGet200ResponseItemsInner from '../model/V1TrainingGet200ResponseItemsInner';
import V1TrainingTrainingIDDelete200Response from '../model/V1TrainingTrainingIDDelete200Response';

/**
* Training service.
* @module api/TrainingApi
* @version 2025-03-25
*/
export default class TrainingApi {

    /**
    * Constructs a new TrainingApi. 
    * @alias module:api/TrainingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDTrainingFilesUploadGet operation.
     * @callback module:api/TrainingApi~v1ReplicasReplicaUUIDTrainingFilesUploadGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate a signed URL for file upload
     * Creates a signed URL for uploading a file to the knowledge base. This is the first step in the file-based training process. The response includes both a signedURL where you can upload your file and a knowledgeBaseID for tracking. After receiving these, use a PUT request to the signedURL to upload your file (with Content-Type: application/octet-stream). The system will automatically extract text from your file, process it, and make it available for your replica to use. Supported file types include PDF, DOCX, and other text-based formats. Files up to 50MB are supported.
     * @param {String} replicaUUID 
     * @param {String} filename The name of the file you want to upload to the knowledge base. This helps identify the file in your knowledge base. Files up to 50MB are supported.
     * @param {module:api/TrainingApi~v1ReplicasReplicaUUIDTrainingFilesUploadGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response}
     */
    v1ReplicasReplicaUUIDTrainingFilesUploadGet(replicaUUID, filename, callback) {
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDTrainingFilesUploadGet");
      }
      // verify the required parameter 'filename' is set
      if (filename === undefined || filename === null) {
        throw new Error("Missing the required parameter 'filename' when calling v1ReplicasReplicaUUIDTrainingFilesUploadGet");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
        'filename': filename
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDTrainingFilesUploadGet200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/training/files/upload', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDTrainingPost operation.
     * @callback module:api/TrainingApi~v1ReplicasReplicaUUIDTrainingPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a knowledge base entry
     * Creates a new empty knowledge base entry for a replica. This is the first step in the text-based training process. After creating the entry, you'll receive a knowledgeBaseID that you'll need to use in the next step to add your training content using the Update endpoint. The entry starts with a BLANK status and will be processed automatically once you add content.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/TrainingApi~v1ReplicasReplicaUUIDTrainingPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDTrainingPost200Response}
     */
    v1ReplicasReplicaUUIDTrainingPost(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDTrainingPost");
      }

      let pathParams = {
        'replicaUUID': replicaUUID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDTrainingPost200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/training', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ReplicasReplicaUUIDTrainingTrainingIDPut operation.
     * @callback module:api/TrainingApi~v1ReplicasReplicaUUIDTrainingTrainingIDPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update knowledge base entry
     * Updates a knowledge base entry with training content. This is the second step in the training process after creating an entry. You can provide \"rawText\" which is the content you want your replica to learn from (such as product information, company policies, or specialized knowledge). The system will automatically process this text and make it available for your replica to use when answering questions. The entry status will change to PROCESSING and then to READY once fully processed.
     * @param {String} replicaUUID 
     * @param {Object} opts Optional parameters
     * @param {Number} [trainingID] 
     * @param {module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest} [v1ReplicasReplicaUUIDTrainingTrainingIDPutRequest] 
     * @param {module:api/TrainingApi~v1ReplicasReplicaUUIDTrainingTrainingIDPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response}
     */
    v1ReplicasReplicaUUIDTrainingTrainingIDPut(replicaUUID, opts, callback) {
      opts = opts || {};
      let postBody = opts['v1ReplicasReplicaUUIDTrainingTrainingIDPutRequest'];
      // verify the required parameter 'replicaUUID' is set
      if (replicaUUID === undefined || replicaUUID === null) {
        throw new Error("Missing the required parameter 'replicaUUID' when calling v1ReplicasReplicaUUIDTrainingTrainingIDPut");
      }

      let pathParams = {
        'replicaUUID': replicaUUID,
        'trainingID': opts['trainingID']
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1ReplicasReplicaUUIDTrainingTrainingIDPut200Response;
      return this.apiClient.callApi(
        '/v1/replicas/{replicaUUID}/training/{trainingID}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1TrainingGet operation.
     * @callback module:api/TrainingApi~v1TrainingGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1TrainingGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all knowledge base entries
     * Returns a list of all knowledge base entries belonging to your organization. This endpoint allows you to view all your training data in one place, with optional filtering by status or type. You can use this to monitor the overall state of your knowledge base, check which entries are still processing, and identify any that might have encountered errors. The response includes detailed information about each entry including its content, status, and metadata.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [status] Filter to show only knowledge base entries with a specific processing status (e.g., READY, PROCESSING, ERR_FILE_PROCESSING)
     * @param {module:model/String} [type] Filter to show only knowledge base entries of a specific type (e.g., text, file_upload, url, training_history)
     * @param {String} [page = '1')] The page number for paginated results (starts at 1). Use this to navigate through large result sets.
     * @param {String} [limit = '100')] The maximum number of knowledge base entries to return per page (up to 100). Use this to control result set size.
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/TrainingApi~v1TrainingGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1TrainingGet200Response}
     */
    v1TrainingGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'status': opts['status'],
        'type': opts['type'],
        'page': opts['page'],
        'limit': opts['limit']
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1TrainingGet200Response;
      return this.apiClient.callApi(
        '/v1/training', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1TrainingTrainingIDDelete operation.
     * @callback module:api/TrainingApi~v1TrainingTrainingIDDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1TrainingTrainingIDDelete200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete knowledge base entry by ID
     * Permanently removes a specific knowledge base entry and its associated vector database entry. Use this endpoint when you need to remove outdated or incorrect training data from your replica's knowledge base. This operation cannot be undone, and the entry will no longer be available for retrieval during conversations with your replica. This endpoint handles the complete cleanup process, removing both the database record and any associated vector embeddings.
     * @param {Object} opts Optional parameters
     * @param {Number} [trainingID] 
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/TrainingApi~v1TrainingTrainingIDDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1TrainingTrainingIDDelete200Response}
     */
    v1TrainingTrainingIDDelete(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'trainingID': opts['trainingID']
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1TrainingTrainingIDDelete200Response;
      return this.apiClient.callApi(
        '/v1/training/{trainingID}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1TrainingTrainingIDGet operation.
     * @callback module:api/TrainingApi~v1TrainingTrainingIDGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1TrainingGet200ResponseItemsInner} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get knowledge base entry by ID
     * Retrieves detailed information about a specific knowledge base entry using its ID. This endpoint returns the complete entry data including its type, status, content, and metadata. You can use this to check the processing status of your training content, view the raw and processed text, and see when it was created and last updated. This is useful for monitoring the progress of your training data as it moves through the processing pipeline.
     * @param {Object} opts Optional parameters
     * @param {Number} [trainingID] 
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/TrainingApi~v1TrainingTrainingIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1TrainingGet200ResponseItemsInner}
     */
    v1TrainingTrainingIDGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'trainingID': opts['trainingID']
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1TrainingGet200ResponseItemsInner;
      return this.apiClient.callApi(
        '/v1/training/{trainingID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
