/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1ReplicasReplicaUUIDTrainingPost400Response from '../model/V1ReplicasReplicaUUIDTrainingPost400Response';
import V1ReplicasReplicaUUIDTrainingPost404Response from '../model/V1ReplicasReplicaUUIDTrainingPost404Response';
import V1ReplicasReplicaUUIDTrainingPost500Response from '../model/V1ReplicasReplicaUUIDTrainingPost500Response';
import V1UsersMeGet200Response from '../model/V1UsersMeGet200Response';
import V1UsersPostRequest from '../model/V1UsersPostRequest';

/**
* Users service.
* @module api/UsersApi
* @version 2025-03-25
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1UsersMeDelete operation.
     * @callback module:api/UsersApi~v1UsersMeDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete the current user
     * This endpoint permanently deletes the currently authenticated user account, including all associated data. After deletion, the account cannot be recovered.
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/UsersApi~v1UsersMeDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    v1UsersMeDelete(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/users/me', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1UsersMeGet operation.
     * @callback module:api/UsersApi~v1UsersMeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1UsersMeGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the current user
     * Returns information about the current user.
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/UsersApi~v1UsersMeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1UsersMeGet200Response}
     */
    v1UsersMeGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1UsersMeGet200Response;
      return this.apiClient.callApi(
        '/v1/users/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1UsersMePut operation.
     * @callback module:api/UsersApi~v1UsersMePutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1UsersMeGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the current user
     * Update the currently logged in user.
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1UsersMeGet200Response} [v1UsersMeGet200Response] 
     * @param {module:api/UsersApi~v1UsersMePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1UsersMeGet200Response}
     */
    v1UsersMePut(opts, callback) {
      opts = opts || {};
      let postBody = opts['v1UsersMeGet200Response'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken', 'UserID'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1UsersMeGet200Response;
      return this.apiClient.callApi(
        '/v1/users/me', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1UsersPost operation.
     * @callback module:api/UsersApi~v1UsersPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1UsersMeGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a user
     * Creates a new user.
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:model/V1UsersPostRequest} [v1UsersPostRequest] 
     * @param {module:api/UsersApi~v1UsersPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1UsersMeGet200Response}
     */
    v1UsersPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['v1UsersPostRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = V1UsersMeGet200Response;
      return this.apiClient.callApi(
        '/v1/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1UsersUserIDGet operation.
     * @callback module:api/UsersApi~v1UsersUserIDGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1UsersMeGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a user by ID
     * Returns information about the user with the specified ID.
     * @param {String} userID 
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIVersion = '2025-03-25')] 
     * @param {module:api/UsersApi~v1UsersUserIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1UsersMeGet200Response}
     */
    v1UsersUserIDGet(userID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'userID' is set
      if (userID === undefined || userID === null) {
        throw new Error("Missing the required parameter 'userID' when calling v1UsersUserIDGet");
      }

      let pathParams = {
        'userID': userID
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Version': opts['xAPIVersion']
      };
      let formParams = {
      };

      let authNames = ['OrganizationServiceToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1UsersMeGet200Response;
      return this.apiClient.callApi(
        '/v1/users/{userID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
