/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.ChatCompletionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChatCompletionsApi', function() {
    describe('v1ExperimentalReplicasReplicaUUIDChatCompletionsPost', function() {
      it('should call v1ExperimentalReplicasReplicaUUIDChatCompletionsPost successfully', function(done) {
        //uncomment below and update the code to test v1ExperimentalReplicasReplicaUUIDChatCompletionsPost
        //instance.v1ExperimentalReplicasReplicaUUIDChatCompletionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDChatCompletionsPost', function() {
      it('should call v1ReplicasReplicaUUIDChatCompletionsPost successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDChatCompletionsPost
        //instance.v1ReplicasReplicaUUIDChatCompletionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
