/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.ReplicasApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReplicasApi', function() {
    describe('v1ReplicasGet', function() {
      it('should call v1ReplicasGet successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasGet
        //instance.v1ReplicasGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasPost', function() {
      it('should call v1ReplicasPost successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasPost
        //instance.v1ReplicasPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDDelete', function() {
      it('should call v1ReplicasReplicaUUIDDelete successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDDelete
        //instance.v1ReplicasReplicaUUIDDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDGet', function() {
      it('should call v1ReplicasReplicaUUIDGet successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDGet
        //instance.v1ReplicasReplicaUUIDGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDPut', function() {
      it('should call v1ReplicasReplicaUUIDPut successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDPut
        //instance.v1ReplicasReplicaUUIDPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
