/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.TelegramIntegrationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TelegramIntegrationApi', function() {
    describe('v1ReplicasReplicaUUIDChatCompletionsTelegramPost', function() {
      it('should call v1ReplicasReplicaUUIDChatCompletionsTelegramPost successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDChatCompletionsTelegramPost
        //instance.v1ReplicasReplicaUUIDChatCompletionsTelegramPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDChatHistoryTelegramGet', function() {
      it('should call v1ReplicasReplicaUUIDChatHistoryTelegramGet successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDChatHistoryTelegramGet
        //instance.v1ReplicasReplicaUUIDChatHistoryTelegramGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDChatHistoryTelegramPost', function() {
      it('should call v1ReplicasReplicaUUIDChatHistoryTelegramPost successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDChatHistoryTelegramPost
        //instance.v1ReplicasReplicaUUIDChatHistoryTelegramPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDIntegrationsTelegramDelete', function() {
      it('should call v1ReplicasReplicaUUIDIntegrationsTelegramDelete successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDIntegrationsTelegramDelete
        //instance.v1ReplicasReplicaUUIDIntegrationsTelegramDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ReplicasReplicaUUIDIntegrationsTelegramPost', function() {
      it('should call v1ReplicasReplicaUUIDIntegrationsTelegramPost successfully', function(done) {
        //uncomment below and update the code to test v1ReplicasReplicaUUIDIntegrationsTelegramPost
        //instance.v1ReplicasReplicaUUIDIntegrationsTelegramPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
