/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest', function() {
    it('should create an instance of V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest', function() {
      // uncomment below and update the code to test V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest
      //var instance = new SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();
      //expect(instance).to.be.a(SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest);
    });

    it('should have the property messages (base name: "messages")', function() {
      // uncomment below and update the code to test the property messages
      //var instance = new SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property store (base name: "store")', function() {
      // uncomment below and update the code to test the property store
      //var instance = new SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property discordData (base name: "discord_data")', function() {
      // uncomment below and update the code to test the property discordData
      //var instance = new SensayApi.V1ExperimentalReplicasReplicaUUIDChatCompletionsPostRequest();
      //expect(instance).to.be();
    });

  });

}));
