/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData', function() {
    it('should create an instance of V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData', function() {
      // uncomment below and update the code to test V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be.a(SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData);
    });

    it('should have the property channelId (base name: "channel_id")', function() {
      // uncomment below and update the code to test the property channelId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property channelName (base name: "channel_name")', function() {
      // uncomment below and update the code to test the property channelName
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property authorId (base name: "author_id")', function() {
      // uncomment below and update the code to test the property authorId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property authorName (base name: "author_name")', function() {
      // uncomment below and update the code to test the property authorName
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property messageId (base name: "message_id")', function() {
      // uncomment below and update the code to test the property messageId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property serverId (base name: "server_id")', function() {
      // uncomment below and update the code to test the property serverId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

    it('should have the property serverName (base name: "server_name")', function() {
      // uncomment below and update the code to test the property serverName
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryPostRequestDiscordData();
      //expect(instance).to.be();
    });

  });

}));
