/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest', function() {
    it('should create an instance of V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest', function() {
      // uncomment below and update the code to test V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();
      //expect(instance).to.be.a(SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest);
    });

    it('should have the property rawText (base name: "rawText")', function() {
      // uncomment below and update the code to test the property rawText
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property processedText (base name: "processedText")', function() {
      // uncomment below and update the code to test the property processedText
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property vectorEntryId (base name: "vectorEntryId")', function() {
      // uncomment below and update the code to test the property vectorEntryId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingTrainingIDPutRequest();
      //expect(instance).to.be();
    });

  });

}));
