/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1ReplicasGet200ResponseItemsInner', function() {
    it('should create an instance of V1ReplicasGet200ResponseItemsInner', function() {
      // uncomment below and update the code to test V1ReplicasGet200ResponseItemsInner
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be.a(SensayApi.V1ReplicasGet200ResponseItemsInner);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property purpose (base name: "purpose")', function() {
      // uncomment below and update the code to test the property purpose
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property shortDescription (base name: "shortDescription")', function() {
      // uncomment below and update the code to test the property shortDescription
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property greeting (base name: "greeting")', function() {
      // uncomment below and update the code to test the property greeting
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property ownerID (base name: "ownerID")', function() {
      // uncomment below and update the code to test the property ownerID
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property _private (base name: "private")', function() {
      // uncomment below and update the code to test the property _private
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property whitelistEmails (base name: "whitelistEmails")', function() {
      // uncomment below and update the code to test the property whitelistEmails
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property profileImage (base name: "profileImage")', function() {
      // uncomment below and update the code to test the property profileImage
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property suggestedQuestions (base name: "suggestedQuestions")', function() {
      // uncomment below and update the code to test the property suggestedQuestions
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property llm (base name: "llm")', function() {
      // uncomment below and update the code to test the property llm
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property voicePreviewText (base name: "voicePreviewText")', function() {
      // uncomment below and update the code to test the property voicePreviewText
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property profileImage (base name: "profile_image")', function() {
      // uncomment below and update the code to test the property profileImage
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property shortDescription (base name: "short_description")', function() {
      // uncomment below and update the code to test the property shortDescription
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property introduction (base name: "introduction")', function() {
      // uncomment below and update the code to test the property introduction
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property ownerUuid (base name: "owner_uuid")', function() {
      // uncomment below and update the code to test the property ownerUuid
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property voiceEnabled (base name: "voice_enabled")', function() {
      // uncomment below and update the code to test the property voiceEnabled
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property videoEnabled (base name: "video_enabled")', function() {
      // uncomment below and update the code to test the property videoEnabled
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property chatHistoryCount (base name: "chat_history_count")', function() {
      // uncomment below and update the code to test the property chatHistoryCount
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property systemMessage (base name: "system_message")', function() {
      // uncomment below and update the code to test the property systemMessage
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property discordIntegration (base name: "discord_integration")', function() {
      // uncomment below and update the code to test the property discordIntegration
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property telegramIntegration (base name: "telegram_integration")', function() {
      // uncomment below and update the code to test the property telegramIntegration
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property elevenLabsID (base name: "elevenLabsID")', function() {
      // uncomment below and update the code to test the property elevenLabsID
      //var instance = new SensayApi.V1ReplicasGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

  });

}));
