/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException', function() {
    it('should create an instance of V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException', function() {
      // uncomment below and update the code to test V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();
      //expect(instance).to.be.a(SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();
      //expect(instance).to.be();
    });

    it('should have the property cause (base name: "cause")', function() {
      // uncomment below and update the code to test the property cause
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();
      //expect(instance).to.be();
    });

    it('should have the property stack (base name: "stack")', function() {
      // uncomment below and update the code to test the property stack
      //var instance = new SensayApi.V1ReplicasReplicaUUIDTrainingPost500ResponseInnerException();
      //expect(instance).to.be();
    });

  });

}));
