/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData', function() {
    it('should create an instance of V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData', function() {
      // uncomment below and update the code to test V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be.a(SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData);
    });

    it('should have the property chatType (base name: "chat_type")', function() {
      // uncomment below and update the code to test the property chatType
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be();
    });

    it('should have the property chatId (base name: "chat_id")', function() {
      // uncomment below and update the code to test the property chatId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be();
    });

    it('should have the property messageId (base name: "message_id")', function() {
      // uncomment below and update the code to test the property messageId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be();
    });

    it('should have the property messageThreadId (base name: "message_thread_id")', function() {
      // uncomment below and update the code to test the property messageThreadId
      //var instance = new SensayApi.V1ReplicasReplicaUUIDChatHistoryTelegramPostRequestTelegramData();
      //expect(instance).to.be();
    });

  });

}));
