/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1TrainingGet200ResponseItemsInner', function() {
    it('should create an instance of V1TrainingGet200ResponseItemsInner', function() {
      // uncomment below and update the code to test V1TrainingGet200ResponseItemsInner
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be.a(SensayApi.V1TrainingGet200ResponseItemsInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property replicaUuid (base name: "replica_uuid")', function() {
      // uncomment below and update the code to test the property replicaUuid
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property filename (base name: "filename")', function() {
      // uncomment below and update the code to test the property filename
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property rawText (base name: "raw_text")', function() {
      // uncomment below and update the code to test the property rawText
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property processedText (base name: "processed_text")', function() {
      // uncomment below and update the code to test the property processedText
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SensayApi.V1TrainingGet200ResponseItemsInner();
      //expect(instance).to.be();
    });

  });

}));
