/**
 * Sensay API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SensayApi);
  }
}(this, function(expect, SensayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SensayApi.WebhookRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebhookRequest', function() {
    it('should create an instance of WebhookRequest', function() {
      // uncomment below and update the code to test WebhookRequest
      //var instance = new SensayApi.WebhookRequest();
      //expect(instance).to.be.a(SensayApi.WebhookRequest);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SensayApi.WebhookRequest();
      //expect(instance).to.be();
    });

    it('should have the property table (base name: "table")', function() {
      // uncomment below and update the code to test the property table
      //var instance = new SensayApi.WebhookRequest();
      //expect(instance).to.be();
    });

    it('should have the property schema (base name: "schema")', function() {
      // uncomment below and update the code to test the property schema
      //var instance = new SensayApi.WebhookRequest();
      //expect(instance).to.be();
    });

    it('should have the property record (base name: "record")', function() {
      // uncomment below and update the code to test the property record
      //var instance = new SensayApi.WebhookRequest();
      //expect(instance).to.be();
    });

    it('should have the property oldRecord (base name: "old_record")', function() {
      // uncomment below and update the code to test the property oldRecord
      //var instance = new SensayApi.WebhookRequest();
      //expect(instance).to.be();
    });

  });

}));
